### ISSUE TITLE
salmon file in different location than expected

### ISSUE THREAD

**Issue by lpantano** [hbc/bcbioRNASeq#1]
a general question:

My last bcbio run has the count data like this:

`run$sample_dirs[samples], "salmon", "quant.sf")`

but the code assume: 

`run$sample_dirs[samples], "salmon", "quant", "quant.sf")`

https://github.com/hbc/bcbioRnaseq/blob/master/R/read_bcbio.R#L48

so @roryk, something changed or we expect to have the `quant.sf` file inside the `sample/salmon/quant.sf`?

**Comment by roryk** [comment]
Yeah it should be in just samples/salmon/quant.sf now I think.

**Comment by mjsteinbaugh** [comment]
I can confirm for sailfish that it previously output to `sailfish/quant/quant.sf`. If there are differences in the sample count structure over the last couple of months, we could just search in each sample directory for the `quant.sf` file instead.

**Comment by mjsteinbaugh** [comment]
Fixed to search for quant.sf file in sample directories
