### ISSUE TITLE
MAplot with lfcShrink

### ISSUE THREAD

**Issue by lpantano** [hbc/bcbioRNASeq#10]
Adaptation of MAplot to show how much the `lfcShrink()` function affects

**Comment by vbarrera** [comment]
Thinking to add "shrink" option to plotMA. However, the plot accepts res object and I need shrunken and unshrunken results. The plan is to feed the function with a bcbio object with these slots or should I add new parameters (i.e unshrunken)?

**Comment by mjsteinbaugh** [comment]
@vbarrera That's a good question. We're using the generic from `BiocGenerics::plotMA`, which is defined as `function (object, …)`. We can provide S4 method (`setMethod()`) support for `DESeqResults` as the primary object. Maybe we should pass in the `resUnshrunken` here and add an optional `resShrunken` parameter argument that we can then require to be a `DESeqResults` object as well.

**Comment by mjsteinbaugh** [comment]
Or maybe the easier option is to just pass in the unshrunken `DESeqResults` and set a parameter argument `shrink = TRUE` that would then calculate the shrunken `DESeqResults` internally from the unshrunken `DESeqResults`. This is probably simpler but we'd have to hardcode the shrinkage parameters, like `coef = 2`.

**Comment by lpantano** [comment]
I like the idea of the method with an extra parameter to accept the shrunken data. I’d avoid to calculate the shrinking inside the function.

**Comment by mjsteinbaugh** [comment]
That makes sense. How about this – we pass the unshrunken `DESeqResults` as the primary object then add a parameter called `lfcShrink` that requires the output from `DESeq2::lfcShrink()`, a shrunken `DESeqResults`. We can add checking in the function with `is(lfcShrink, "DESeqResults")`. That should work.

**Comment by vbarrera** [comment]
Usually, we're working with the shrunken results (downstream analysis) so we should pass the unshrunken results as optional. So, shrink option should default to NULL but if exists (being a DESeqResults object), plot the shrinkage. Would that be ok? In this case the is(lfcShrink, "DESeqResults") won't work as it's not shrunken.

**Comment by mjsteinbaugh** [comment]
Right but I think in this case the parameter naming wouldn't be intuitive. How about this instead – we pass the **shrunken** `DESeqResults` in as the primary object, then have a parameter argument called `unshrunken` that supports an unshrunken `DESeqResults`. Like you mentioned, let's have this set to `NULL` but default, but if it exists, then check that it's a `DESeqResults` object (`is(unshrunken, "DESeqResults")`). All the `is()` statement would do is check that the secondary object is a `DESeqResults`, but maybe there's a way to check inside these objects and tell whether they're shrunken or not.

**Comment by mjsteinbaugh** [comment]
Closing this issue and moving to the projects pinboard
