### ISSUE TITLE
Error: package or namespace load failed for ‘IRanges’

### ISSUE THREAD

**Issue by vladsavelyev** [hbc/bcbioRNASeq#100]
Hey,

I've installed the package through conda on a linux machine, into a clean conda installation:

```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p ./miniconda
export PATH=$(pwd)/miniconda/bin:$PATH
conda create -n bcbio_rnaseq -c bioconda r-bcbiornaseq -y
source activate bcbio_rnaseq
```

But when I load the library, it crashes with the following error:

```
R -e "library(bcbioRNASeq)"
...
Error: package or namespace load failed for ‘IRanges’:
 Functions found when exporting methods from the namespace ‘IRanges’ which are not S4 generic: ‘endoapply’, ‘mendoapply’
Execution halted
```

Am I doing anything wrong?

**Comment by vladsavelyev** [comment]
Hoping updating of `variantannotation` https://github.com/bioconda/bioconda-recipes/pull/8942 will fix it.

UPD: Updating just `variantannotation` requires updating of its dependencies, which ultimately requires updates for the whole bioconductor... and I'm not ready to do that manually for over a hundred packages :( So I'll just forget output conda, I guess

**Comment by mjsteinbaugh** [comment]
Thanks, we'll look into this. [IRanges](https://bioconductor.org/packages/release/bioc/html/IRanges.html) is a standard Bioconductor package and should install with conda cleanly. Maybe the [bioconductor-iranges](https://bioconda.github.io/recipes/bioconductor-iranges/README.html) recipe needs some tweaking.

**Comment by vladsavelyev** [comment]
Guys, this PR was the source of the error: https://github.com/bioconda/bioconda-recipes/pull/8925#issuecomment-389606748

So need to either pin `bioconductor-s4vectors<0.18`, or wait for CI to ok in my PR above, and risk to merge it. I'll let you know if either works.

**Comment by vladsavelyev** [comment]
The PR fixed that, and 

```
conda update -y bioconductor-iranges
``` 

resolves the problem!

Closing the issue.

**Comment by vladsavelyev** [comment]
Hah, now having this:

```
Error: package or namespace load failed for ‘GenomicRanges’:
 Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’
Error: package ‘GenomicRanges’ could not be loaded
Execution halted
```

Will play a bit more, bit It's likely we'd have to downgrade packages, after all.

**Comment by vladsavelyev** [comment]
Resolved that; just needed to

```
conda update -y bioconductor-genomicranges bioconductor-xvector
```

As well.

Now getting to this one:

```
Error: package or namespace load failed for 'bcbioRNASeq' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'DEGreport' 1.12.0 is being loaded, but >= 1.14 is required
```

**Comment by vladsavelyev** [comment]
Just updated `bioconductor-degreport` (1.14 was already the latest on bioconda), and all works!

**Comment by mjsteinbaugh** [comment]
For reference, the conda issue with IRanges seems to be related to accidental PR merges of Bioconductor 3.7 packages. conda doesn't support Bioc 3.7 yet because it requires R 3.4.

https://github.com/bioconda/bioconda-recipes/issues/8947
