### ISSUE TITLE
Support for other count formats

### ISSUE THREAD

**Issue by ohofmann** [hbc/bcbioRNASeq#103]
Following up on the Slack discussion: we are mostly relying on STAR and HiSat2 alignments for (low cellularity) tumor RNA-Seq. It would be great if we could use count data generated from these two aligners within the bcbioRNASeq environment, most likely through the `express` ([repo](https://pachterlab.github.io/eXpress/overview.html)) quantification approach.

**Comment by mjsteinbaugh** [comment]
Perfect we'll work on adding those to the `caller` argument of the [`bcbioRNASeq()`](http://bioinformatics.sph.harvard.edu/bcbioRNASeq/reference/bcbioRNASeq.html) constructor.

**Comment by mjsteinbaugh** [comment]
Hi @ohofmann I'm working on pushing this update. Will ping you when it's done.

**Comment by mjsteinbaugh** [comment]
Support for `caller = "star"` or `caller = "hisat2"` has been added to the pending v0.2.6 release. Internally, this works by loading the featureCounts data from the `combined.counts` file inside the bcbio project directory.

**Comment by ohofmann** [comment]
Thanks a lot!
