### ISSUE TITLE
Has v0.2.5 been released?

### ISSUE THREAD

**Issue by corburn** [hbc/bcbioRNASeq#110]
Commit 9b3a46844e5d01e383fdeaab4350b3e869027f05  and 52402caa4327124d6f6ece147a7266b567563c94 bump the version to 0.2.5, but it has not been tagged or marked for [release](https://github.com/hbc/bcbioRNASeq/releases). Has v0.2.5 been released?

**Comment by mjsteinbaugh** [comment]
Hi @corburn v0.2.5 is currently on the master branch. I'll make a release so we can update conda. Thanks!
