### ISSUE TITLE
Sample mixup when sample name starts with a number

### ISSUE THREAD

**Issue by fredrikka** [hbc/bcbioRNASeq#117]
Hi,

I encountered that samples are mixed up when importing with project with bcbioRNASeq and sample names are beginning with a number.  I think the problem is in `bcbioRNASeq:::.tximport`
`sampleDirs` will be prefixed with an X in R and then `sampleDirs` and `files` will not match. 
```
files <- list.files(path = file.path(sampleDirs, type), 
            pattern = "quant.sf", full.names = TRUE, recursive = TRUE)
```
I think this line is the causing of the problem:
`names(files) <- names(sampleDirs)`

/Fredrik

**Comment by roryk** [comment]
Hi Fredrik,

So sorry about this, that is definitely a known bug. We ended up fixing it in bcbio, so now samplenames prefaced with a number get an X stuck in front in bcbio.

**Comment by fredrikka** [comment]
Thanks, 

I worked around it by manually renaming the sample dirs in the final directory.

**Comment by roryk** [comment]
Thanks-- sorry again for the problem, future bcbio runs won't have this issue.
