### ISSUE TITLE
Error in getVarianceStabilizedData(cds): is(cds, "CountDataSet") is not TRUE

### ISSUE THREAD

**Issue by jxshi** [hbc/bcbioRNASeq#126]
Hi,

I encountered the following error message when trying to run bcbioRNAseq Differential Expression step. Here is the error message.
```
Quitting from lines 152-160 (DE.Rmd) 
Error in getVarianceStabilizedData(cds) : 
  is(cds, "CountDataSet") is not TRUE
Calls: <Anonymous> ... .nextMethod -> .local -> getVarianceStabilizedData -> stopifnot
Execution halted
```

But I can run the whole process when I run step by step in R.

Can you help me figure out how to solve this problem please? TIA!

Best,
Jianxiang

**Comment by mjsteinbaugh** [comment]
Thanks @jxshi, I'll take a look. I suspect that this is a DESeq2-specific issue related to your dataset. Do you have a copy of the corresponding bcbioRNASeq object or the DESeqDataSet object that I can load up?

Mike

**Comment by mjsteinbaugh** [comment]
@jxshi I'm having trouble reproducing this issue. If you have an example dataset, I can take a look, otherwise I'd recommend re-posting in the [Bioconductor support forum](https://support.bioconductor.org/) with a `deseq2` tag.

**Comment by jxshi** [comment]
Hi Mike,

Sorry for the late reply. I was out of town for a few days. Here is the link to the [DESeqDataSet object](https://minersutep-my.sharepoint.com/:u:/g/personal/jshi_utep_edu/Ec0Zht0uRx9JrOsjB_mEHP0BxfA-o9foyS38-f0ZFNXq3Q?e=u56T3u). This link will expire in 7 days. Thank you for help!

Best,

Jianxiang

**Comment by jxshi** [comment]
Hi Mike, 

I was able to run the "Differential Expression Analysis" rmarkdown file chunk by chunk. When I tried to knit the results to html file, it popped up the mentioned error message. Hope this information gives you more clue on how to debug. Thanks!

Best,

Jianxiang

**Comment by mjsteinbaugh** [comment]
Thanks I'll see if I can figure it out today.

**Comment by jxshi** [comment]
Hi,

I have another RNAseq project encountered the same problem. I was able to run the ```Differential Expression Analysis``` rmarkdown code chunk by chunk.

Here is the error message:
```
Error in getVarianceStabilizedData(cds) : 
  is(cds, "CountDataSet") is not TRUE
Calls: <Anonymous> ... .nextMethod -> .local -> getVarianceStabilizedData -> stopifnot
Execution halted
```

Hope that helps!

Best,

Jianxiang

**Comment by jxshi** [comment]
Hi, 

I have encountered new error message when running a new set of data, which seems quite weird. 

Here is the new error message:
```
Error in cleanContrast(object, contrast, expanded = isExpanded, listValues = listValues, : as control is the reference level, was expecting phenotype_treatment50uM_vs_control to be present in 'resultsNames(object)'
```

What do you think triggered this error message?

Thank you!

Best,
Jianxiang

**Comment by mjsteinbaugh** [comment]
Hi @jxshi, what does `resultsNames(object)` return on your DESeqDataSet? Otherwise, you can set `contrastSamples = FALSE` for those functions and it will plot all samples instead.

**Comment by jxshi** [comment]
Hi,

```resultsNames(object)``` returns ```character(0)``` on my DESeqDataSet. And I have figured what triggered the following error message:
```
Error in cleanContrast(object, contrast, expanded = isExpanded, listValues = listValues, : as control is the reference level, was expecting phenotype_treatment50uM_vs_control to be present in 'resultsNames(object)'
```

 I set ```dds$phenotype``` to three different levels, ```control```, ```treatment30uM```, and ```treatment50uM```. When I checked what ```dds$phenotype``` returned, I found that ```treatment30uM``` had been coerced to ```treatment30u_m``` and ```treatment50uM``` had been coerced to ```treatment50u_m```. When I set ```numerator = "treatment50u_m"```, I was able to knit this ```Differential Expression Analysis``` to ```html``` results.

Maybe you can check why these different levels has been coerced to lower case letters?

Thank you and cheers!

Best,
Jianxiang

**Comment by jxshi** [comment]
Hi @mjsteinbaugh ,

I have solved this problem by deleting all related files in the folder to re-knit the ```rmarkdown``` file to ```html``` results.

Cheers!
Jianxiang

**Comment by mjsteinbaugh** [comment]
Nice! I’ll add a troubleshooting note about Markdown caching in the README
