### ISSUE TITLE
error loading bcbio data into bcbiornaseq  R object

### ISSUE THREAD

**Issue by PatrickJReed** [hbc/bcbioRNASeq#128]
Any help in this would be greatly appreciated.

>repairseq_bcbV2 <- bcbioRNASeq(uploadDir = "/raidixshare_log-g/Dylan/RepairSeq/RepairSeq_Salmon_072019/final", interestingGroups = c("batch", "celltype"), organism = "Homo sapiens")
2019-07-21_RepairSeq_Salmon_072019

114 samples detected:
A54Fibs_4d_A, A54UNA_4d_A, A54UNG_4d_A, A54UNG_4d_B, E30UNA_4d_A, E30UNG_4d_A...
Reading project-summary.yaml
Parsed with column specification:
cols(
  genome = col_character(),
  resource = col_character(),
  version = col_character()
)
Reading sample metadata from YAML
Reading sample metrics from YAML
Parsed with column specification:
cols(
  transcriptID = col_character(),
  geneID = col_character()
)
Reading salmon counts using tximport 1.10.1
1 Parsed with column specification:
cols(
  Name = col_character(),
  Length = col_double(),
  EffectiveLength = col_double(),
  TPM = col_double(),
  NumReads = col_double()
)
Error in readBin(bootCon, "integer", n = expected.n) :
  invalid 'n' argument
In addition: Warning message:
In evalq(as.numeric(sequenceLength), <environment>) :
  NAs introduced by coercion

>traceback()

10: readBin(bootCon, "integer", n = expected.n)
9: value[[3L]](cond)
8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
7: tryCatchList(expr, classes, parentenv, handlers)
6: tryCatch({
       bootsIn <- readBin(bootCon, "double", n = expected.n)
       stopifnot(length(bootsIn) == expected.n)
       bootsIn
   }, error = function(...) {
       close(bootCon)
       bootCon <- gzcon(file(file.path(auxPath, "bootstrap", "bootstraps.gz"),
           "rb"))
       readBin(bootCon, "integer", n = expected.n)
   })
5: readInfRepFish(x, type)
4: infRepImporter(dirname(files[i]))
3: tximport(files = files, type = type, txIn = txIn, txOut = txOut,
       countsFromAbundance = "lengthScaledTPM", tx2gene = tx2gene,
       ignoreTxVersion = ignoreTxVersion, importer = read_tsv)
2: .tximport(sampleDirs = sampleDirs, type = caller, txIn = TRUE,
       txOut = txOut, tx2gene = tx2gene)
1: bcbioRNASeq(uploadDir = "/raidixshare_log-g/Dylan/RepairSeq/RepairSeq_Salmon_072019/final",
       interestingGroups = c("batch", "celltype"), organism = "Homo sapiens")

**Comment by roryk** [comment]
Hi Patrick,

This is due to having an out-of-date tximport which is incompatible with the new version of Salmon. If you upgrade your version of tximport like this:

```
bcbio_conda install -c bioconda bioconductor-tximport==1.12.1
```

it should fix this problem.

**Comment by PatrickJReed** [comment]
Fixed. Thank you!

**Comment by roryk** [comment]
Great, thanks for following up!
