### ISSUE TITLE
bioconda package

### ISSUE THREAD

**Issue by roryk** [hbc/bcbioRNASeq#130]
Hey @mjsteinbaugh,

There is a new bioconda bot which pushes new releases automatically when it spies new releases, unfortunately this means the bioconda recipe for bcbioRNASeq is broken since it won't have all of the new dependencies, as they are not in bioconda and aren't listed in the bcbioRNASeq recipe. I think these two are missing:

```
    DESeqAnalysis (>= 0.2.0)
    acidplots (>= 0.2.7)
```

**Comment by roryk** [comment]
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/r-bcbiornaseq/meta.yaml has the current dependency list.

```
   - r-base
    - bioconductor-summarizedexperiment
    - r-bcbiobase
    - bioconductor-deseq2
    - bioconductor-degreport
    - bioconductor-edger
    - r-ggrepel
    - r-pbapply
    - bioconductor-tximport
    - bioconductor-vsn
    - r-rmarkdown
    - r-tidyverse
    - bioconductor-genomeinfodbdata
    - r-hexbin
```

looks like it is also missing the bioverbs dependency.

**Comment by mjsteinbaugh** [comment]
@roryk I’m working on updating the recipes today

**Comment by roryk** [comment]
Thanks!

**Comment by mjsteinbaugh** [comment]
bioconda update is in progress.
