### ISSUE TITLE
Installation of bcbioRNASeq for R 3.6.1

### ISSUE THREAD

**Issue by marypiper** [hbc/bcbioRNASeq#132]
I have been trying to install the most recent version of bcbioRNASeq, and I get the error below. I can't seem to get around it and wondered if it is an issue with the latest release. 

Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.1
  (2019-07-05)
Installing github package(s) 'acidgenomics/bioverbs'
Downloading GitHub repo acidgenomics/bioverbs@master
Running `R CMD build`...
* checking for file ‘/private/var/folders/lt/mp0j8dgn1kd05zzjrklvswf80000gn/T/RtmpJ6UR62/remotes2bd40a6b6fd/acidgenomics-bioverbs-11d2641/DESCRIPTION’ ... OK
* preparing ‘bioverbs’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘bioverbs_0.2.3.tar.gz’
*   Trying 13.35.78.86...
* TCP_NODELAY set
* Connected to bioconductor.org (13.35.78.86) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; CN=*.bioconductor.org
*  start date: Oct  5 14:24:38 2016 GMT
*  expire date: Oct  3 18:30:38 2019 GMT
*  subjectAltName: host "bioconductor.org" matched cert's "bioconductor.org"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> GET /biocLite.R HTTP/1.1
Host: bioconductor.org
User-Agent: libcurl/7.54.0
Accept: */*
< HTTP/1.1 200 OK
< Content-Length: 8355
< Connection: keep-alive
< Server: Apache/2.4.18 (Ubuntu)
< Last-Modified: Wed, 05 Jun 2019 12:00:02 GMT
< Accept-Ranges: bytes
< Date: Thu, 08 Aug 2019 12:39:20 GMT
< ETag: "20a3-58a925659f7b8"
< Cache-Control: max-age=60
< X-Cache: Hit from cloudfront
< Via: 1.1 52c5c6677e1ddc37f9c7ddc8eee96130.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: BOS50-C1
< X-Amz-Cf-Id: Yuthid1-eHcT9TL7OCTbCBED5EjXpy2FBtPngQtiROCnmdoUaF_5RQ==
< 
* Connection #0 to host bioconductor.org left intact
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
Execution halted
Error: Failed to install 'bioverbs' from GitHub:
  (converted from warning) installation of package ‘/var/folders/lt/mp0j8dgn1kd05zzjrklvswf80000gn/T//RtmpJ6UR62/file2bd137bd34/bioverbs_0.2.3.tar.gz’ had non-zero exit status

**Comment by mjsteinbaugh** [comment]
Hi @marypiper, that seems to be an issue with BiocManager. Try using `remotes::install_github()` instead.

**Comment by marypiper** [comment]
Hey @mjsteinbaugh I had tried `remotes::install_github()` first, then tried the `install()` function, but I received the same message with that as well.

**Comment by marypiper** [comment]
This is the error message from `remotes::install_github()` below in case there is something different about it:

```
remotes::install_github("hbc/bcbioRNASeq")
Downloading GitHub repo hbc/bcbioRNASeq@master
Downloading GitHub repo acidgenomics/DESeqAnalysis@master
Downloading GitHub repo acidgenomics/acidplots@master
Downloading GitHub repo acidgenomics/basejump@master
Downloading GitHub repo acidgenomics/bioverbs@master
Running `R CMD build`...
* checking for file ‘/private/var/folders/lt/mp0j8dgn1kd05zzjrklvswf80000gn/T/RtmpDPeyDT/remotes68b52b31472/acidgenomics-bioverbs-11d2641/DESCRIPTION’ ... OK
* preparing ‘bioverbs’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘bioverbs_0.2.3.tar.gz’
*   Trying 13.249.188.80...
* TCP_NODELAY set
* Connected to bioconductor.org (13.249.188.80) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; CN=*.bioconductor.org
*  start date: Oct  5 14:24:38 2016 GMT
*  expire date: Oct  3 18:30:38 2019 GMT
*  subjectAltName: host "bioconductor.org" matched cert's "bioconductor.org"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> GET /biocLite.R HTTP/1.1
Host: bioconductor.org
User-Agent: libcurl/7.54.0
Accept: */*

< HTTP/1.1 200 OK
< Content-Length: 8355
< Connection: keep-alive
< Server: Apache/2.4.18 (Ubuntu)
< Last-Modified: Wed, 05 Jun 2019 12:00:02 GMT
< Accept-Ranges: bytes
< Date: Thu, 08 Aug 2019 13:52:36 GMT
< ETag: "20a3-58a925659f7b8"
< Cache-Control: max-age=60
< X-Cache: RefreshHit from cloudfront
< Via: 1.1 1c4cb605a68bbe1d1bbce1a363445388.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: BOS50-C2
< X-Amz-Cf-Id: EEQ958NPdCr1bxJYVrEflGF-B3iGpxxYdZEIWL3GMzw2lAmMhCsWjQ==
< 
* Connection #0 to host bioconductor.org left intact
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
Execution halted
Error: Failed to install 'bcbioRNASeq' from GitHub:
  Failed to install 'DESeqAnalysis' from GitHub:
  Failed to install 'acidplots' from GitHub:
  Failed to install 'basejump' from GitHub:
  Failed to install 'bioverbs' from GitHub:
  (converted from warning) installation of package ‘/var/folders/lt/mp0j8dgn1kd05zzjrklvswf80000gn/T//RtmpDPeyDT/file68b6b0372c8/bioverbs_0.2.3.tar.gz’ had non-zero exit status
```

**Comment by mjsteinbaugh** [comment]
Weird are you running R on O2?

**Comment by marypiper** [comment]
No, on my local machine

**Comment by mjsteinbaugh** [comment]
I just tried installing on my virtual machine running Red Hat and it seems to work. I'll look around online and see if anybody else has hit this before

**Comment by marypiper** [comment]
okay, thanks Mike!

**Comment by marypiper** [comment]
@mjsteinbaugh , I found some other packages not working with my R installation, so I think it might be specific to my computer. Please don't worry about it for now. I will continue to troubleshoot on my end.
