### ISSUE TITLE
Future Impovements Suggestion

### ISSUE THREAD

**Issue by kokyriakidis** [hbc/bcbioRNASeq#145]
Hi @mjsteinbaugh !

I will just point out here some future imporvement suggestions:

1) Transcript level analysis with sleuth
2) DTU with DRIMSeq and DEXSeq
3) Would be nice to be able to ran the analysis with DESeq2 EdgeR Limma Sleuth and have a way to summarize the results of all these for DGE
4) Likelihood Ratio Test Support

And to make this incredible it would be nice to integrade them into RMarkdown templates :)
The point is to make this package an all in one solution for every RNASeq analysis.

**Comment by mjsteinbaugh** [comment]
Thanks @kokyriakidis I'll work on incorporating some of these suggestions.

**Comment by mjsteinbaugh** [comment]
@kokyriakidis Getting back to these points, I think the way to go is to have bcbioRNASeq act as a handoff to sleuth, DEXSeq, DRIMSeq, limma, etc. I'm working on an update that improves support for simple coercion of the `bcbioRNASeq` object into the starting material required for these packages.

**Comment by mjsteinbaugh** [comment]
Closing issue, as these feature requests have been added to the TODO list
