### ISSUE TITLE
error loading DESeqAnalysis 

### ISSUE THREAD

**Issue by sjmonkley** [hbc/bcbioRNASeq#149]
Running v 0.3.31 with latest Markdown template but get an error loading package DESeqAnalysis. Not sure if I should have reported the issue there but as I have a history here I thought I would continue. Looks like its looking to acidplots for upset rather than UpsetR?

```
library(DESeqAnalysis)
Error: package or namespace load failed for 'DESeqAnalysis':
 object 'upset' is not exported by 'namespace:acidplots'
```

**Comment by mjsteinbaugh** [comment]
What's this look like?

```r
packageVersion("basejump")
packageVersion("acidplots")
packageVersion("DESeqAnalysis")
```

**Comment by sjmonkley** [comment]
sorry for the delay. DESeqAnalysis had not updated due to issues with required packages not installing. I fixed it by loading them manually so now they are all up to date its working.
Thanks

**Comment by mjsteinbaugh** [comment]
Perfect, good to hear!
