### ISSUE TITLE
vst counts are not defined in object.

### ISSUE THREAD

**Issue by tiger815** [hbc/bcbioRNASeq#159]
Hi,

When I try to analyze my samples using this pipeline, the following error occurs in PlotPCA.
-----------------------------------------------------
> plotPCA(object1, label = FALSE)
ℹ Using `vst` counts.
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': vst counts are not defined in object.
-----------------------------------------------------

Samples were successfully loaded with the following options.
-----------------------------------------------------
# GeneID, normalization
object1 <- bcbioRNASeq(
  uploadDir = "/data/home/tiger815/seq_raw_data/ipsc_CM_doxo/samples/final/",
  level = "genes",
  organism = "Homo sapiens",
  genomeBuild = "hg38",
  fast = TRUE
)
-----------------------------------------------------

Could you give me some advice?

Many thanks,

**Comment by mjsteinbaugh** [comment]
Thanks I'll take a look. What version of bcbioRNASeq are you currently using? Note that VST counts don't get calculated with the `fast = TRUE` option, so this error is expected. However, I'll work on improving the error message for `plotPCA` in this case.

**Comment by mjsteinbaugh** [comment]
For reference, here's a minimal reprex:

```r
library(bcbioRNASeq)
uploadDir <- system.file("extdata/bcbio", package = "bcbioRNASeq")
object <- bcbioRNASeq(uploadDir = uploadDir, fast = TRUE)
plotPCA(object)
```

**Comment by mjsteinbaugh** [comment]
Improved the error message regarding this issue in the pending v0.3.37 release. Thanks for the heads up!
