### ISSUE TITLE
Data Import error message

### ISSUE THREAD

**Issue by tiger815** [hbc/bcbioRNASeq#161]
Bcbio nextgen ver 1.2.3.
R 4.0.2

Hi~
I'm getting a lot of help from your awesome package.

I found one error in this package. When loading bcbio RNA-seq data after executing standard bulk RNAseq, an error seems to occur because the combined.counts file was missing. This file was placed in a folder called featureCounts, a subfolder of the final folder.
I copied the combined.counts file from the featureCounts folder to the upper folder to solve the error. After that, I had no problem loading the data.

Bcbio nextgen ver 1.2.3.
R 4.0.2

Thanks, 

-----------------------
# GeneID, normalization : move annotated.count file up to directory..
object1 <- bcbioRNASeq(
  uploadDir = ("/data/home/tiger815/seq_raw_data/ipsc_CM_doxo/samples/final"),
  caller = "star",
  level = "genes",
  organism = "Homo sapiens",
  genomeBuild = "hg38"
)

---------------------------
── bcbioRNASeq ───────────────────────────────────────────────────────────────────────────────
Importing bcbio-nextgen RNA-seq run

── Run info ──

uploadDir: /data/home/tiger815/seq_raw_data/ipsc_CM_doxo/samples/final
projectDir: 2020-09-15_samples

→ Sanitizing sample names: `DOXO-1nM_rep1, DOXO-1nM_rep2, DOXO-1nM_rep3, DOXO-5nM1, DOXO-5nM2, DOXO-5nM3, DOXO-cont1, DOXO-c....`.
9 samples detected:
    ● DOXO_1nM_rep1
    ● DOXO_1nM_rep2
    ● DOXO_1nM_rep3
    ● DOXO_5nM1
    ● DOXO_5nM2
    ● DOXO_5nM3
    ● DOXO_cont1
    ● DOXO_cont2
    ● DOXO_cont3

→ Importing project-summary.yaml at /data/home/tiger815/seq_raw_data/ipsc_CM_doxo/samples/final/2020-09-15_samples using yaml::`yaml.load_file()`.
→ Importing data_versions.csv at /data/home/tiger815/seq_raw_data/ipsc_CM_doxo/samples/final/2020-09-15_samples using vroom::`vroom()`.
→ Importing programs.txt at /data/home/tiger815/seq_raw_data/ipsc_CM_doxo/samples/final/2020-09-15_samples using vroom::`vroom()`.
→ Importing bcbio-nextgen.log at /data/home/tiger815/seq_raw_data/ipsc_CM_doxo/samples/final/2020-09-15_samples using readr::`read_lines()`.
→ Importing bcbio-nextgen-commands.log at /data/home/tiger815/seq_raw_data/ipsc_CM_doxo/samples/final/2020-09-15_samples using readr::`read_lines()`.

── Sample metadata ──

→ Getting sample metadata from YAML.
→ Getting sample quality control metrics from YAML.

── Counts ──

── featureCounts 
→ Slotting aligned counts into primary `counts()` assay.
→ Importing aligned counts from featureCounts.
Error in import(file = file.path(projectDir, "combined.counts")) : 
  Assert failure.
[1] isAFile(file) || isAURL(file) is not TRUE.

**Comment by mjsteinbaugh** [comment]
Ah thanks, the directory structure has been reorganized a bit with the bcbio-nextgen v1.2.3 release. I'll fix this in bcbioRNASeq to reflect the `featureCounts` directory change.

**Comment by mjsteinbaugh** [comment]
@tiger815 Can you paste the directory structure of the bcbio output using `tree`?
I'm setting up a new test run to check the changes in bcbio v1.2.3.

The featureCounts matrix has been moved from `bcbio/YYYY-MM-DD_bcbio/combined.counts` to `bcbio/YYYY-MM-DD_bcbio/featureCounts/combined.counts`, and we need to reflect this change in the R code.

**Comment by tiger815** [comment]
Hi @mjsteinbaugh, 
Sure. 

This is the result of 'tree' executed in 'final' directory of Bcbio bulk RNAseq output directory.
I hope it helps to fix the bug.


.
├── 2020-09-15_samples
│?? ├── counts
│?? ├── featureCounts
│?? ├── multiqc
│?? │?? ├── multiqc_data
│?? │?? └── report
│?? │??     └── metrics
│?? ├── tpm
│?? └── transcriptome
├── DOXO-1nM_rep1
│?? ├── qc
│?? │?? ├── fastqc
│?? │?? ├── qualimap_rnaseq
│?? │?? │?? └── DOXO-1nM_rep1
│?? │?? │??     └── css
│?? │?? ├── salmon
│?? │?? ├── samtools
│?? │?? └── star
│?? ├── salmon
│?? │?? ├── aux_info
│?? │?? │?? └── bootstrap
│?? │?? ├── libParams
│?? │?? └── logs
│?? └── STAR
├── DOXO-1nM_rep2
│?? ├── qc
│?? │?? ├── fastqc
│?? │?? ├── qualimap_rnaseq
│?? │?? │?? └── DOXO-1nM_rep2
│?? │?? │??     └── css
│?? │?? ├── salmon
│?? │?? ├── samtools
│?? │?? └── star
│?? ├── salmon
│?? │?? ├── aux_info
│?? │?? │?? └── bootstrap
│?? │?? ├── libParams
│?? │?? └── logs
│?? └── STAR
├── DOXO-1nM_rep3
│?? ├── qc
│?? │?? ├── fastqc
│?? │?? ├── qualimap_rnaseq
│?? │?? │?? └── DOXO-1nM_rep3
│?? │?? │??     └── css
│?? │?? ├── salmon
│?? │?? ├── samtools
│?? │?? └── star
│?? ├── salmon
│?? │?? ├── aux_info
│?? │?? │?? └── bootstrap
│?? │?? ├── libParams
│?? │?? └── logs
│?? └── STAR
├── DOXO-5nM1
│?? ├── qc
│?? │?? ├── fastqc
│?? │?? ├── qualimap_rnaseq
│?? │?? │?? └── DOXO-5nM1
│?? │?? │??     └── css
│?? │?? ├── salmon
│?? │?? ├── samtools
│?? │?? └── star
│?? ├── salmon
│?? │?? ├── aux_info
│?? │?? │?? └── bootstrap
│?? │?? ├── libParams
│?? │?? └── logs
│?? └── STAR
├── DOXO-5nM2
│?? ├── qc
│?? │?? ├── fastqc
│?? │?? ├── qualimap_rnaseq
│?? │?? │?? └── DOXO-5nM2
│?? │?? │??     └── css
│?? │?? ├── salmon
│?? │?? ├── samtools
│?? │?? └── star
│?? ├── salmon
│?? │?? ├── aux_info
│?? │?? │?? └── bootstrap
│?? │?? ├── libParams
│?? │?? └── logs
│?? └── STAR
├── DOXO-5nM3
│?? ├── qc
│?? │?? ├── fastqc
│?? │?? ├── qualimap_rnaseq
│?? │?? │?? └── DOXO-5nM3
│?? │?? │??     └── css
│?? │?? ├── salmon
│?? │?? ├── samtools
│?? │?? └── star
│?? ├── salmon
│?? │?? ├── aux_info
│?? │?? │?? └── bootstrap
│?? │?? ├── libParams
│?? │?? └── logs
│?? └── STAR
├── DOXO-cont1
│?? ├── qc
│?? │?? ├── fastqc
│?? │?? ├── qualimap_rnaseq
│?? │?? │?? └── DOXO-cont1
│?? │?? │??     └── css
│?? │?? ├── salmon
│?? │?? ├── samtools
│?? │?? └── star
│?? ├── salmon
│?? │?? ├── aux_info
│?? │?? │?? └── bootstrap
│?? │?? ├── libParams
│?? │?? └── logs
│?? └── STAR
├── DOXO-cont2
│?? ├── qc
│?? │?? ├── fastqc
│?? │?? ├── qualimap_rnaseq
│?? │?? │?? └── DOXO-cont2
│?? │?? │??     └── css
│?? │?? ├── salmon
│?? │?? ├── samtools
│?? │?? └── star
│?? ├── salmon
│?? │?? ├── aux_info
│?? │?? │?? └── bootstrap
│?? │?? ├── libParams
│?? │?? └── logs
│?? └── STAR
└── DOXO-cont3
    ├── qc
    │?? ├── fastqc
    │?? ├── qualimap_rnaseq
    │?? │?? └── DOXO-cont3
    │?? │??     └── css
    │?? ├── salmon
    │?? ├── samtools
    │?? └── star
    ├── salmon
    │?? ├── aux_info
    │?? │?? └── bootstrap
    │?? ├── libParams
    │?? └── logs
    └── STAR

**Comment by mjsteinbaugh** [comment]
This should be fixed in bcbioRNASeq v0.3.39! Apologies for the delay in pushing the bug fix.

See related pull request https://github.com/hbc/bcbioRNASeq/pull/164
