### ISSUE TITLE
NameSpace error

### ISSUE THREAD

**Issue by yfukasawa** [hbc/bcbioRNASeq#165]
Hello,

Thanks for developing and maintaining a nice package.
I recently reinstalled bcbioRNAseq through conda (+env), and the version is 0.3.37.

After loading the library, I faced below error, probably related to the name space issue with acidgenerics.

`Error: package or namespace load failed for 'bcbioRNASeq' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'acidgenerics'`

After some struggling, it looks that it went through by downgrading acidgenerics package from 0.4.1 to 0.3.14 through conda.
At least loading was successful after this downgrading.

Could you please look at some codes? acidgenerics ver. 0.4.1 looks pretty new, so 0.4.0 might be compatible. but I just didn't try.
Thanks.

Yoshinori

**Comment by mjsteinbaugh** [comment]
Thanks @yfukasawa , I'm working on a bioconda recipe update for `r-bcbiornaseq` 0.3.39 (https://github.com/bioconda/bioconda-recipes/pull/24747), and will let you know when that is available.

**Comment by mjsteinbaugh** [comment]
OK this should be fixed for v0.3.39.
