### ISSUE TITLE
Error in .local(object, ...) :    unused argument (DESeqDataSet = new("DESeqDataSet", design = ~phenotype, dispersionFunction = function (q) 

### ISSUE THREAD

**Issue by gongmeiyuan** [hbc/bcbioRNASeq#169]
Hi,

I am currently using bcbioRNASeq_0.3.40 and it worked fantastic for Homo sapiens. However, when I analyzed Homo sapiens data, the Differential Expression analyses templates did not go through, but it got stuck in the  Differential Expression analyses  step. with the following errors popped up

> ```
>   |...........................................................           |  85%
>   ordinary text without R code
> 
>   |.............................................................         |  87%
> label: results-tables
> Quitting from lines 300-318 (treatment1_vs_control_DiffExpr.rmd) 
> Error in .local(object, ...) : 
>   unused argument (DESeqDataSet = new("DESeqDataSet", design = ~phenotype, dispersionFunction = function (q) 
> coefs[1] + coefs[2]/q, rowRanges = new("GRanges", seqnames = new("Rle", values = c(23, 20, 1, 6, 1, 23, 6, 3, 7, 12, 7, 11, 4, 23, 4, 7, 17, 7, 12, 23, 2, 7, 16, 2, 3, 8, 7, 17, 3, 1, 4, 12, 1, 3, 17, 12, 7, 19, 16, 7, 6, 3, 7, 23, 7, 17, 7, 23, 17, 16, 19, 7, 23, 4, 7, 17, 7, 17, 12, 16, 19, 9, 17, 7, 23, 16, 17, 7, 2, 7, 16, 6, 11, 13, 16, 17, 23, 17, 7, 16, 19, 17, 11, 16, 11, 17, 7, 16, 17, 16, 7, 14, 7, 11, 1, 7, 2, 11, 7, 19, 7, 19, 17, 7, 19, 7, 17, 7, 23, 17, 12, 5, 2, 16, 19, 4, 19, 17, 
> 19, 17, 1, 23, 11, 16, 3, 16, 6, 1, 6, 23, 1, 6, 23, 6, 23, 1, 6, 3, 7, 17, 3, 7, 12, 3, 19, 12, 19, 8, 16, 22, 17, 8, 2, 3, 8, 1, 7, 6, 23, 1, 6, 1, 14, 6, 7, 6, 1, 12, 17, 3, 7, 12, 3, 12, 19, 3, 19, 12, 23, 9, 16, 12, 23, 6, 1, 6, 1, 17, 5, 12, 14, 19, 17, 3, 23, 19, 17, 7, 17, 19, 11, 3, 11, 19, 7, 19, 9, 12, 19, 2, 19, 16, 23, 17, 19, 3, 23, 3, 8, 12, 6, 10, 24, 12, 14, 2,
> Calls: render ... eval -> eval -> mapply -> <Anonymous> -> <Anonymous>
> 
> Execution halted

```
Here is the rmarkdown file of the Differential Expression analyses
[treatment1_vs_control_DiffExpr.zip](https://github.com/hbc/bcbioRNASeq/files/6040577/treatment1_vs_control_DiffExpr.zip)

And I'm so sorry to update a zip file about the code.It's my first time to Issues a question that I don't konw how to put a link here.

Here is the output of sessionInfo():
> sessionInfo('bcbioRNASeq')
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /public/home/zzumpc08/miniconda3/envs/r-base/lib/libblas.so.3.8.0
LAPACK: /public/home/zzumpc08/miniconda3/envs/r-base/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C             
 [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8    
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8   
 [7] LC_PAPER=en_US.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C      

attached base packages:
character(0)

other attached packages:
[1] bcbioRNASeq_0.3.40

loaded via a namespace (and not attached):
[1] compiler_4.0.3  graphics_4.0.3  utils_4.0.3     grDevices_4.0.3
[5] stats_4.0.3     datasets_4.0.3  methods_4.0.3   base_4.0.3

**Comment by mjsteinbaugh** [comment]
Thanks @gongmeiyuan I’m taking a look and will get back to you with an update

**Comment by gongmeiyuan** [comment]
This is the file about
\bcb.rds
\bcb_dds.rds
\bcb_dt.rds
\bcb_res_list_shrunken.rds
\bcb_res_list_unshrunken.rds



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hbc/bcbioRNASeq"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 中午1:19
收件人:&nbsp;"hbc/bcbioRNASeq"<bcbioRNASeq@noreply.github.com&gt;;
抄送:&nbsp;"995834426"<995834426@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hbc/bcbioRNASeq] Error in .local(object, ...) :    unused argument (DESeqDataSet = new("DESeqDataSet", design = ~phenotype, dispersionFunction = function (q)  (#169)





 
Thanks @gongmeiyuan I’m taking a look and will get back to you with an update
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

2021-02-24.zip (74.16M, 2021年03月27日 13:33 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=71653435eb576899085f6f0e1634074d0650000d03020c011f060001001901040b01190c5157574f56560d02520501570a540c01303a35500257051800061850064b4e5c403408&code=2e45045b

**Comment by gongmeiyuan** [comment]
This link is about the file I was used in Differential Expression analyses step
\bcb.rds
\bcb_dds.rds
\bcb_dt.rds
\bcb_res_list_shrunken.rds
\bcb_res_list_unshrunken.rds

(http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=71653435eb576899085f6f0e1634074d0650000d03020c011f060001001901040b01190c5157574f56560d02520501570a540c01303a35500257051800061850064b4e5c403408&code=2e45045b)

**Comment by mjsteinbaugh** [comment]
Can you try repeating with these enabled in the R session:

options(
    "error" = quote(rlang::entrace()),
    "rlang_backtrace_on_error" = "full",
    "rstudio.errors.suppressed" = FALSE
)
This is really helpful for debugging. Thanks!

**Comment by gongmeiyuan** [comment]
I'm sorry to reply so late
after I repeating with the code, the reply is this 

```
Error in .local(object, ...) : 
  unused argument (DESeqDataSet = new("DESeqDataSet", design = ~phenotype, dispersionFunction = function (q) 
coefs[1] + coefs[2]/q, rowRanges = new("GRanges", seqnames = new("Rle", values = c(23, 20, 1, 6, 1, 23, 6, 3, 7, 12, 7, 11, 4, 23, 4, 7, 17, 7, 12, 23, 2, 7, 16, 2, 3, 8, 7, 17, 3, 1, 4, 12, 1, 3, 17, 12, 7, 19, 16, 7, 6, 3, 7, 23, 7, 17, 7, 23, 17, 16, 19, 7, 23, 4, 7, 17, 7, 17, 12, 16, 19, 9, 17, 7, 23, 16, 17, 7, 2, 7, 16, 6, 11, 13, 16, 17, 23, 17, 7, 16, 19, 17, 11, 16, 11, 17, 7, 16, 17, 16, 7, 14, 7, 11, 1, 7, 2, 11, 7, 19, 7, 19, 17, 7, 19, 7, 17, 7, 23, 17, 12, 5, 2, 16, 19, 4, 19, 17, 
19, 17, 1, 23, 11, 16, 3, 16, 6, 1, 6, 23, 1, 6, 23, 6, 23, 1, 6, 3, 7, 17, 3, 7, 12, 3, 19, 12, 19, 8, 16, 22, 17, 8, 2, 3, 8, 1, 7, 6, 23, 1, 6, 1, 14, 6, 7, 6, 1, 12, 17, 3, 7, 12, 3, 12, 19, 3, 19, 12, 23, 9, 16, 12, 23, 6, 1, 6, 1, 17, 5, 12, 14, 19, 17, 3, 23, 19, 17, 7, 17, 19, 11, 3, 11, 19, 7, 19, 9, 12, 19, 2, 19, 16, 23, 17, 19, 3, 23, 3, 8, 12, 6, 10, 24, 12, 14, 2,
```

**Comment by mjsteinbaugh** [comment]
OK thanks I'm working on fixing this issue today

**Comment by mjsteinbaugh** [comment]
@gongmeiyuan Does this draft version of a revised differential expression template work for you?
https://github.com/acidgenomics/r-bcbiornaseq/blob/master/inst/rmarkdown/templates/02-differential-expression/skeleton/skeleton.Rmd

**Comment by mjsteinbaugh** [comment]
This error should be fixed in the forthcoming update. Please reopen if this issue persists.
