### ISSUE TITLE
Bcbio run with 2 callers

### ISSUE THREAD

**Issue by kokyriakidis** [hbc/bcbioRNASeq#172]
Hi @mjsteinbaugh !

What happens when I run bcbio with both salmon and kallisto and generate a bcbioRNASeq object? Will bcbioRNASeq choose salmon generated counts over kallisto? I just want to use kallisto results for DTE with sleuth, not for DGE.

**Comment by mjsteinbaugh** [comment]
Sure, this is defined by the `caller` and `level` arguments defined in `bcbioRNASeq()`, but must be run separately (and saved into distinct objects).

Refer to the [`bcbioRNASeq()`](https://r.acidgenomics.com/packages/bcbiornaseq/reference/bcbioRNASeq.html) documentation for details, in particular the `"caller"` argument.

```r
## Gene-level counts from salmon.
bcb_salmon_genes <- bcbioRNASeq(
    uploadDir = "final",
    level = "genes",
    caller = "salmon",
    countsFromAbundance = "lengthScaledTPM",
    fast = TRUE
)

## Transcript-level counts from kallisto for DTE with sleuth.
bcb_kallisto_transcripts <- bcbioRNASeq(
    uploadDir = "final",
    level = "transcripts",
    caller = "kallisto",
    fast = TRUE
)
```

**Comment by kokyriakidis** [comment]
The default is `salmon` if I do not specify a caller?

**Comment by kokyriakidis** [comment]
Thanks for the info!
