### ISSUE TITLE
Labels are not showing in plotVolcano

### ISSUE THREAD

**Issue by kokyriakidis** [hbc/bcbioRNASeq#173]
Hi @mjsteinbaugh ,

I run an analysis using the DE template and everything works perfectly except the Volcano plot. It cannot show top gene labels

```
> plotVolcano(object = deseq, i = 1L, ntop = 10L)
→ category_AD_vs_Control (shrunken LFC)
ℹ 34 non-unique gene symbols detected.
ℹ Labeling 10 genes in plot.
Warning message:
Removed 10 rows containing missing values (geom_label_repel). 
```

![image](https://user-images.githubusercontent.com/33731293/126850827-77d6b1ea-1f67-406a-b53c-73845cc32dba.png)

Have you any idea why I get missing values? Every other plot (eg. MA) correctly show labels for top genes.

![image](https://user-images.githubusercontent.com/33731293/126850856-538d1f8d-18e6-43ab-ba20-75118ae37712.png)

Best,
KK

**Comment by mjsteinbaugh** [comment]
OK thanks I'll check that today

**Comment by mjsteinbaugh** [comment]
You're right, this appears to be a bug in DESeqAnalysis 0.4.2. I'm working on pushing a fix. Here's a reprex:

```r
packageVersion("DESeqAnalysis")
## [1] ‘0.4.2’
library(DESeqAnalysis)
data(deseq)
plotVolcano(object = deseq, i = 1L, ntop = 10L)
Warning: Removed 10 rows containing missing values (geom_label_repel).
```

**Comment by mjsteinbaugh** [comment]
OK this should be fixed in [DESeqAnalysis](https://github.com/acidgenomics/r-deseqanalysis) 0.4.3. I'm pushing that recipe update to conda as well.
