### ISSUE TITLE
Functional Analysis issues

### ISSUE THREAD

**Issue by kokyriakidis** [hbc/bcbioRNASeq#174]
Hi @mjsteinbaugh !

In Functional Analysis template I found some errors:

1. In params `results_name: "group_treatment_vs_control"` should change to `results_name: "treatment_vs_control"` without the `group`. Otherwise I get an error in `res <- results(deseq, i = params$results_name)`

2. `names(lfc_vec) <- rownames(sig_res_df)` should change to `names(lfc_vec) <- rownames(sig_res)` because `sig_res_df` does not exist.
 
3. I get an error in KEGG enrichment analysis when I try to run `ensembl2entrez <- Ensembl2Entrez(object = dds, format = "1:1")`. I get:

```
Error in .local(object, ...) : Assert failure. [1] isSubset(x = c("geneId", "entrezId"), y = colnames(mcols(object))) is not TRUE. Cause: 'c("geneId", "entrezId")' has elements not in 'colnames(mcols(object))': entrezId
```
It needs a list of genes if I understand correctly? I tried to feed it with `ensembl2entrez <- Ensembl2Entrez(object = deseq@transform@rowRanges@ranges@NAMES, format = "1:1")` but got:
```
→ Matching identifiers using NCBI `OrgDb` via AnnotationHub 3.0.1.
ℹ "AH92581" (org.Hs.eg.db.sqlite): NCBI gene ID based annotations about Homo sapiens.
Error in .getEnsembl2EntrezFromOrgDb(keys = object, keytype = "ENSEMBL",  : 
  Match failure: ENSG00000002079, ENSG00000005955, ENSG00000006074, ENSG00000006075, ENSG00000006114, ENSG00000017373, ENSG00000017621, ENSG00000031544, ENSG00000034063, ENSG00000049319, ENSG00000056661, ENSG00000.....

```

When I try the example code
```
genes <- c("ENSG00000000003", "ENSG00000000005")
x <- Ensembl2Entrez(object = genes, organism = organism)
```

It runs OK. When I run the same code using 2 ENSG keys from my data I get an error:
```
> genes <- c("ENSG00000002079", "ENSG00000005955")
> x <- Ensembl2Entrez(object = genes, organism = params$organism)
→ Matching identifiers using NCBI `OrgDb` via AnnotationHub 3.0.1.
ℹ "AH92581" (org.Hs.eg.db.sqlite): NCBI gene ID based annotations about Homo sapiens.
Error in .testForValidKeys(x, keys, keytype, fks) : 
  None of the keys entered are valid keys for 'ENSEMBL'. Please use the keys method to see a listing of valid arguments.
```

I saw that the following codes yields a NULL:
```
## Entrez identifiers must be defined in the "entrezId" column of DESeqDataSet
## rowData, otherwise this step will fail.
ranked_list_entrez <-
    tryCatch(
        expr = {
            x <- RankedList(
                object = deseq,
                value = "stat",
                keyType = "entrezId"
            )
            x <- x[[params$results_name]]
            x
        },
        error = function(e) NULL
    )
eval_entrez <- is.numeric(ranked_list_entrez)
```
However this step does not fail. `eval_entrez` is FALSE in my case. How do I correct this?

**Comment by mjsteinbaugh** [comment]
Thanks @kokyriakidis , I'm looking into this today

**Comment by mjsteinbaugh** [comment]
Let's revisit this issue with the bcbioRNASeq v0.3.42 update. Please feel free to reopen if the issues persist with the updated conda recipe.
