### ISSUE TITLE
DESeq2 plot functions not found with bcbioRNASeq 

### ISSUE THREAD

**Issue by VictoriaPatten** [hbc/bcbioRnaseq#184]
Hi, I am using bcbioRNASeq and working from the linked workflow paper: Steinbaugh MJ, Pantano L, Kirchner RD, Barrera V, Chapman BA, Piper ME, Mistry M, Khetani RS, Rutherford KD, Hoffman O, Hutchinson JN, Ho Sui SJ. (2018).

I have gone through all of the QC steps and created the plots no problem, but now when I move on to the Differential Expression Analysis using DESeq2 I keep running into trouble. I keep getting errors like `Error in plotMeanAverage(res) : could not find function "plotMeanAverage"` and the same happens for the plotVolcano(res). The alphaSummary function was also not found. 

Please can you advise on how to proceed as I can't seem to create any DGE plots. 

Is there updated documentation on using bcbioRNASeq and doing DGE analysis, or is the 2018 article above the only one? 

Thanks.

**Comment by mjsteinbaugh** [comment]
Hi @VictoriaPatten , I need to revise the F1000 workflow paper a bit, as we've changed a couple of the functions slightly:

- Ensure our [DESeqAnalysis](https://r.acidgenomics.com/packages/deseqanalysis/) package is installed and loaded.
- Use [`plotMA`](https://r.acidgenomics.com/packages/deseqanalysis/reference/plotMA.html) instead of `plotMeanAverage`.
- [`alphaSummary`](https://r.acidgenomics.com/packages/deseqanalysis/reference/alphaSummary.html), which works on `DESeqDataSet` input, is now defined in DESeqAnalysis instead of bcbioRNASeq.

Current DE template is here, for reference: https://github.com/hbc/bcbioRNASeq/blob/master/inst/rmarkdown/templates/02-differential-expression/skeleton/skeleton.Rmd

Recommended installation methods: either use our [bioconda recipe](https://bioconda.github.io/recipes/r-bcbiornaseq/README.html) or install in R with:

```r
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
install.packages(
    pkgs = "bcbioRNASeq",
    repos = c(
        "https://r.acidgenomics.com",
        BiocManager::repositories()
    ),
    dependencies = TRUE
)
```

**Comment by VictoriaPatten** [comment]
Thanks @mjsteinbaugh, this is very helpful. I'll install DESeqAnalysis package and hopefully all will come right. 
Thanks.

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh I've followed the template you linked above and all the plots worked beautifully until the very end where we get to 'TopTables'. Here I keep getting the error:

![Screenshot from 2022-05-13 11-39-53](https://user-images.githubusercontent.com/53177709/168257275-bda3661e-5d06-4f4e-8840-07edddb5b06e.png)

I ran rowData on the dds object and this is the output:

![Screenshot from 2022-05-13 11-40-47](https://user-images.githubusercontent.com/53177709/168257425-21ff469b-2f2e-4728-b222-b4566fef9085.png)

Is the issue that I have Ensemble ID's not gene names?
How can I get this TopTables function to work?

Thanks very much
Victoria

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh and @roryk Do you have any advice on my above problem? I've followed the template and run it as a script in R and have also used the markdown template in Rstudio and keep getting the same error (attached above) when I reach the Top Tables section. 

Can you advise? 
Thanks.
Victoria

**Comment by mjsteinbaugh** [comment]
@VictoriaPatten I can reproduce this with a minimal DESeq2 example, and will post a bug fix to DESeqAnalysis later today. Will be in touch with an update!

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh Thanks so much. I can share my bcb.rds file through googledrive, but obviously cannot upload it here on GitHub due to ethics and confidentiality of patient data etc. Can I use mike@steinbaugh.com or do you have a different preferred email?

**Comment by mjsteinbaugh** [comment]
Not necessary, I think I made a minimal test dataset that covers your issue. Thanks though!

**Comment by mjsteinbaugh** [comment]
OK try installing [DESeqAnalysis](https://r.acidgenomics.com/packages/deseqanalysis/) 0.6.1 and see if that resolves your issue:

```r
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
install.packages(
    pkgs = "DESeqAnalysis",
    repos = c(
        "https://r.acidgenomics.com",
        BiocManager::repositories()
    ),
    dependencies = TRUE
)
```

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh I had already installed this. I've just reinstalled and run it again now to check and I am still getting the exact same error. 
![image](https://user-images.githubusercontent.com/53177709/169091326-a9851aa6-7cb0-4803-8820-a4f2ce72cc78.png)

**Comment by mjsteinbaugh** [comment]
What does `packageVersion("DESeqAnalysis")` return? Make sure to rerun in a clean R session. That error message was only defined in the preivous version.

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh Okay I think I see the issue. I only have R/4.1.1 at the moment and DESeqAnalysis will only load V0.5.0. I will get the system admin to upgrade to R/4.2.0 and re install. Hopefully that will do the trick! Will be in touch if I hit any more stumbling blocks. 
Thank you. 
P.S. I am very new to bioinformatics, so your help is greatly appreciated.

**Comment by mjsteinbaugh** [comment]
Ah OK yeah that's it, try upgrading to R 4.2 / Bioconductor 3.15. There are a number of changes in Bioconductor 3.15 that make it difficult to continue providing compatiblity support with the R 4.1 release series.

PS You can check your Bioconductor version with:

```r
BiocManager::version()
```

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh, the version upgrade seemed to help but now I get a new error after the Top Table section, right at the end of the template. Lines 368-372

```label: export-results
→ Exporting <DESeqDataSet> to 'data'.
→ Exporting <SummarizedExperiment> to '/home/hocine/my-projects/victoria/rnaseq/results/2022-05-19/differential-expression/data'.
→ Exporting assays "counts", "normalized", "fpkm" to '/home/hocine/my-projects/victoria/rnaseq/results/2022-05-19/differential-expression/data'.
Quitting from lines 368-372 (bcb_template.Rmd)
Error in `fileExt()`:
! unused argument (pattern = compressExtPattern)
Backtrace:
  1. BiocIO::export(object = deseq, con = params[["results_dir"]])
  2. DESeqAnalysis::export(object = deseq, con = params[["results_dir"]])
  3. DESeqAnalysis .local(object, con, format, ...)
  5. DESeqAnalysis::export(...)
  6. DESeqAnalysis .local(object, con, format, ...)
     ...
 10. AcidExperiment:::.exportAssays(...)
 12. base::lapply(...)
 13. AcidExperiment FUN(X[[i]], ...)
 15. pipette::export(...)
 16. pipette .local(object, con, format, ...
```

I don't know how to fix this error as it seems it is related to the source code?
Thanks

**Comment by mjsteinbaugh** [comment]
It sounds like you may need to upgrade some other packages. What returns when you run this?

```r
BiocManager::valid(site_repository = "https://r.acidgenomics.com")
```

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh that returns:
[1] TRUE

**Comment by mjsteinbaugh** [comment]
OK great, what do these return on your machine?

```r
vapply(
    X = c(
        "AcidBase",
        "AcidExperiment",
        "AcidGenerics",
        "DESeqAnalysis",
        "basejump",
        "bcbioBase",
        "bcbioRNASeq",
        "goalie",
        "pipette",
        "syntactic"
    ),
    FUN = function(x) {
        as.character(packageVersion(x))
    },
    FUN.VALUE = character(1L)
)
```

```r
print(AcidBase::fileExt)
```

**Comment by VictoriaPatten** [comment]
```
> vapply(
+     X = c(
+         "AcidBase",
+         "AcidExperiment",
+         "AcidGenerics",
+         "DESeqAnalysis",
+         "basejump",
+         "bcbioBase",
+         "bcbioRNASeq",
+         "goalie",
+         "pipette",
+         "syntactic"
+     ),
+     FUN = function(x) {
+         as.character(packageVersion(x))
+     },
+     FUN.VALUE = character(1L)
+ )
      AcidBase AcidExperiment   AcidGenerics  DESeqAnalysis       basejump 
       "0.6.1"        "0.4.0"        "0.6.2"        "0.6.1"       "0.16.0" 
     bcbioBase    bcbioRNASeq         goalie        pipette      syntactic 
       "0.8.0"        "0.5.0"        "0.6.3"        "0.9.1"        "0.6.0" 
> 
> print(AcidBase::fileExt)
function (path) 
{
    pos <- regexpr(pattern = extPattern, text = path, ignore.case = TRUE)
    ifelse(test = pos > -1L, yes = substring(text = path, first = pos + 
        1L), no = NA_character_)
}
<bytecode: 0x55a2745474c0>
<environment: namespace:AcidBase>
```

**Comment by mjsteinbaugh** [comment]
Ah OK I need to push a minor fix to `r-acidbase`. Thanks, this is helpful!

**Comment by mjsteinbaugh** [comment]
This should be resolved with [AcidBase](https://r.acidgenomics.com/packages/acidbase/) v0.6.2. Try updating with:

```r
if (![requireNamespace](https://rdrr.io/r/base/ns-load.html)("BiocManager", quietly = TRUE)) {
    [install.packages](https://rdrr.io/r/utils/install.packages.html)("BiocManager")
}
[install.packages](https://rdrr.io/r/utils/install.packages.html)(
    pkgs = "AcidBase",
    repos = [c](https://rdrr.io/r/base/c.html)(
        "https://r.acidgenomics.com",
        BiocManager::[repositories](https://rdrr.io/pkg/BiocManager/man/repositories.html)()
    ),
    dependencies = TRUE
)
```

edit: this got messed up from copy and paste from pkgdown website, see below

**Comment by VictoriaPatten** [comment]
When I try to run this in R/4.2.0 I get:

```
> if (![requireNamespace](https://rdrr.io/r/base/ns-load.html)("BiocManager", quietly = TRUE)) {
Error: unexpected '[' in "if (!["
>     [install.packages](https://rdrr.io/r/utils/install.packages.html)("BiocManager")
Error: unexpected '[' in "    ["
> }
Error: unexpected '}' in "}"
> [install.packages](https://rdrr.io/r/utils/install.packages.html)(
Error: unexpected '[' in "["
>     pkgs = "AcidBase",
Error: unexpected ',' in "    pkgs = "AcidBase","
>     repos = [c](https://rdrr.io/r/base/c.html)(
Error: unexpected '[' in "    repos = ["
>         "https://r.acidgenomics.com",
Error: unexpected ',' in "        "https://r.acidgenomics.com","
>         BiocManager::[repositories](https://rdrr.io/pkg/BiocManager/man/repositories.html)()
Error: unexpected '[' in "        BiocManager::["
>     ),
Error: unexpected ')' in "    )"
>     dependencies = TRUE
> )

```

**Comment by mjsteinbaugh** [comment]
My bad, the formatting got messed up from Markdown:

```r
if (![requireNamespace](https://rdrr.io/r/base/ns-load.html)("BiocManager", quietly = TRUE)) {
    [install.packages](https://rdrr.io/r/utils/install.packages.html)("BiocManager")
}
[install.packages](https://rdrr.io/r/utils/install.packages.html)(
    pkgs = "AcidBase",
    repos = [c](https://rdrr.io/r/base/c.html)(
        "https://r.acidgenomics.com",
        BiocManager::[repositories](https://rdrr.io/pkg/BiocManager/man/repositories.html)()
    ),
    dependencies = TRUE
)
```

**Comment by mjsteinbaugh** [comment]
Sorry about that, here's the correct code:

```r
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
install.packages(
    pkgs = "AcidBase",
    repos = c(
        "https://r.acidgenomics.com",
        BiocManager::repositories()
    ),
    dependencies = TRUE
)
```

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh Thanks, this seemed to work. When looking at the table output though, _some_ files seem to have the ENS ID's but the top tables (Up-, down-, all-, both.csv) do not have the Ensemble gene ID's. Is this something that can be fixed? Currently I don't see how to identify which genes are differentially expressed in these tables as the rows don't link to specific genes. 
Also, can row names be added to that tables?

Many thanks. 
Victoria

**Comment by mjsteinbaugh** [comment]
Ah good point, I'll work on fixing that

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh, I know this is a lot for you to look into, but while you are fixing the issue above with the ENS ID's,
I've also run into an error with the Functional Analysis template (on RStudio). 
```
Quitting from lines 96-136 (functional_analysis.Rmd) 
Error in `str_match()`:
! could not find function "str_match"
Execution halted
```
And when my colleague ran the template on his machine he got a bit further (somehow?) but then got the error:
```
Quitting from lines 177-196 (functional_analysis.Rmd) 
Error in `alert()`:
! could not find function "alert"
Execution halted
```

Then another thing, because I had done the QC steps from your F1000 paper, not using the rmakdown template, I decided to now go back and re-do the QC using the template, and I'm afraid, more errors:
```
Quitting from lines 223-228 (qc.Rmd) 
Error:
! Assert failure.
[1] hasLength(keep) is not TRUE.
Cause: `keep` has length 0.
Backtrace:
     ▆
  1. ├─BiocIO::export(...)
  2. └─AcidExperiment::export(...)
  3.   └─AcidExperiment .local(object, con, format, ...)
  4.     └─AcidExperiment:::.exportRowData(...)
  5.       ├─AcidGenerics::atomize(data)
  6.       └─pipette::atomize(data)
  7.         └─pipette .local(object, ...)
  8.           ├─AcidGenerics::atomize(object)
  9.           └─pipette::atomize(object)
 10.             └─pipette .local(object, ...)
 11.               └─goalie::assert(hasLength(keep))
 12.                 └─AcidCLI stop(...)
 13.                   └─cli::cli_abort(x, call = NULL)
 14.                     └─rlang::abort(message, ..., call = call, use_cli_format = TRUE)

Execution halted
```

I'm terribly sorry for taking up so much of your time with these errors. Are you able to fix them?
Thank you so much for your help.

**Comment by mjsteinbaugh** [comment]
Hi @VictoriaPatten I'm working on some package updates today, will send an update soon

**Comment by mjsteinbaugh** [comment]
PS `alert` is from AcidCLI, and `str_match` is from stringr

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh have you managed to do those package updates to add ENS ID's to the top tables and also fix the issues in the QC template?

Also, I have both `stringr` and `AcidCLI` packages installed, but I am still getting this error with the functional analysis template.
```
Quitting from lines 96-136 (functional_analysis.Rmd) 
Error in `str_match()`:
! could not find function "str_match"
Execution halted
```

Hope to hear from you soon.
Thanks

**Comment by mjsteinbaugh** [comment]
Hi @VictoriaPatten , I'm working on an update that I'll push soon!

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh, have you been able to finish the updates you were working on?

We ran the functional analysis again and commented out the `alert` function and now there is another error related to the organism. 

The organism of `dds` is Homo Sapiens (with capital S). In line 297 for the `RankedList` we get the error:
```
! Assert failure.
[1] identical(organism(dds), "Homo sapiens") is not TRUE.
```
I don't know which script generated the Homo Sapiens (with capital S), how can I fix this?

Thanks so much
Victoria

**Comment by mjsteinbaugh** [comment]
Hi @VictoriaPatten , I'm working on finishing a couple of updates to bcbioRNASeq, and will try to get those out today if possible. I'll post a link to an updated R Markdown template that you can try out with your dataset.

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh sorry to keep bothering you about this, I'm just on quite a tight time schedule as I have to submit my thesis in 6 weeks time so I really need to get this analysis completed. Have you managed to do the R Markdown template updates?

**Comment by mjsteinbaugh** [comment]
Hi @VictoriaPatten apologies for the delay, as I'm on vacation this week. I'll work on getting this fixed ASAP and ping you back!

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh any update? Are you still on vacation?
I'm still running into issues with the functional analysis template and the Ensemble IDs vs Entrez ID for the GSEA and KEGG analysis, and also still the issue with 'Homo sapiens'

```
Quitting from lines 297-324 (functional_analysis.Rmd) 

Error:
! Assert failure.
[1] identical(organism(dds), "Homo sapiens") is not TRUE.
Backtrace:
    ▆
 1. ├─AcidGSEA::RankedList(object = deseq, value = "stat", keyType = "geneName")
 2. └─AcidGSEA::RankedList(object = deseq, value = "stat", keyType = "geneName")
 3.   └─AcidGSEA .local(object, ...)
 4.     └─goalie::assert(identical(organism(dds), "Homo sapiens"))
 5.       └─AcidCLI stop(...)
 6.         └─cli::cli_abort(x, call = NULL)
 7.           └─rlang::abort(message, ..., call = call, use_cli_format = TRUE)
Warning message:
ggrepel: 1 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
Execution halted

```

Hope to hear from you soon. 
Victoria

**Comment by mjsteinbaugh** [comment]
Hi @VictoriaPatten just got back, I'll work on package updates this week. Apologies for the delay!

**Comment by mjsteinbaugh** [comment]
Hi @VictoriaPatten , quick followup -- I'm blocking out some time tomorrow and Wednesday to to finish this update.

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh Thank you, thank you, thank you!! I am beyond grateful.

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh its been two weeks... were you able to finish the update? I am still getting errors with the functional analysis with ensemble and entrezID issues. I'm a bit desperate with this now.

**Comment by mjsteinbaugh** [comment]
Apologies for the delay, working on it this morning. I'm free to do a Zoom chat this week as well, which may speed up the troubleshooting

**Comment by mjsteinbaugh** [comment]
OK I can confirm that the template is working with my example dataset. I'm working on pushing a couple of updates to AcidGSEA and bcbioRNASeq that should resolve your issues.

**Comment by VictoriaPatten** [comment]
Thats great! I'll run my dataset through and hopefully it will work too. Does your dataset use Ensembl ID's?
Perhaps if I cant get things working by the end of the week we could do that zoom chat on Friday.

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh I am still getting this error:

```
Quitting from lines 374-378 (functional_analysis.Rmd) 
Error:
! Assert failure.
[1] isSubset(x = c("geneId", "entrezId"), y = colnames(mcols(object))) is not
TRUE.
Cause: `c("geneId", "entrezId")` has elements not in `colnames(mcols(object))`:
entrezId
Backtrace:
    ▆
 1. ├─AcidGenerics::Ensembl2Entrez(object = dds, format = "1:1")
 2. └─AcidExperiment::Ensembl2Entrez(object = dds, format = "1:1")
 3.   ├─AcidGenerics::Ensembl2Entrez(rowRanges(object), ...)
 4.   └─AcidGenomes::Ensembl2Entrez(rowRanges(object), ...)
 5.     └─AcidGenomes .local(object, ...)
 6.       └─goalie::assert(isSubset(x = c("geneId", "entrezId"), y = colnames(mcols(object))))
 7.         └─AcidCLI stop(...)
 8.           └─cli::cli_abort(x, call = NULL)
 9.             └─rlang::abort(message, ..., call = call, use_cli_format = TRUE)
Warning messages:
1: ggrepel: 1 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
2: ggrepel: 1 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
Execution halted
```

Does this have something to do with the AcidGSEA update you were going to push? How should I proceed?

**Comment by mjsteinbaugh** [comment]
OK I think the issue with your dataset is that you don't have enough gene metadata in the `rowRanges` / `rowData` of your original `bcbioRNASeq` object to correctly run the clusterProfiler enrichment analysis template with Ensembl-to-Entrez identifier interconversion. This requires setting the `organism` and `ensemblRelease` arguments during the main `bcbioRNASeq()` generator call. Refer to the [bcbioRNASeq documentation](https://r.acidgenomics.com/packages/bcbiornaseq/reference/bcbioRNASeq.html) for details.

Don't worry, you don't need to re-run the analysis from scratch. We just need to tweak your `DESeqAnalysis` object to contain the sufficient Entrez identifier metadata so you can successfully run Ensembl-to-Entrez conversion.

Assuming you have a `DESeqAnalysis` object, generated by our differential expression R Markdown template.

```r
## DESeqAnalysis object
## https://r.acidgenomics.com/packages/deseqanalysis/
## Generated with code like:
## > deseq <- DESeqAnalysis::DESeqAnalysis(
## >   data = <DESeqDataSet>,
## >   transform = <DESeqTransform>,
## >   results = <list of unshrunken results>,
## >   lfcShrink = <list of shrunken results>
## )
```

If you need to assign `rowRanges`, and your data was processed using Ensembl as the reference genome, here's the way. This gets automatically generated by bcbioRNASeq if you use `organism` during the main `bcbioRNASeq()` call.

```r
suppressPackageStartupMessages({
    library(SummarizedExperiment)
    library(AcidGenomes)
})
## NOTE Update the Ensembl release to match the version used in your analysis (e.g. 106).
rowRanges <- makeGRangesFromEnsembl(
    organism = "Homo sapiens",
    release = 106L
)
c("geneId", "entrezId") %in% colnames(mcols(rowRanges))
## If this step errors, you likely have a mismatch with your reference genome.
stopifnot(all(names(rowRanges) %in% rownames(deseq@data)))
## Reorder the GenomicRanges to match your DESeqDataSet.
rowRanges <- rowRanges[rownames(deseq@data)]
## Slot the updated ranges back into your DESeqDataSet and DESeqTransform objects.
rowRanges(deseq@data) <- rowRanges
rowRanges(deseq@transform) <- rowRanges
validObject(deseq)
```

Now your object should contain the desired `geneId` and `entrezId` columns in `rowRanges` metadata required for these GSEA steps. Give that a shot!

**Comment by mjsteinbaugh** [comment]
PS a draft update of the functional analysis template is available here, for reference:

https://github.com/acidgenomics/r-bcbiornaseq/blob/develop/inst/rmarkdown/templates/03-functional-analysis/skeleton/skeleton.Rmd

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh, still having some trouble. The DESeqAnalysis object I'm using was created with the DGE template. 
I added the two libraries into the functional analysis template and then added the rowRanges bit
```
rowRanges <- makeGRangesFromEnsembl(
    organism = "Homo sapiens",
    release = 106L
)
```
And before I can add the rest of the tweak I already get an error at this point. I have tried multiple different release versions (106L/107L etc) but I still get the error:

```
→ Making <GenomicRanges> from Ensembl.

Quitting from lines 98-102 (functional_analysis.Rmd) 
Error:
! Namespace failure: AnnotationHub.
Backtrace:
    ▆
 1. └─AcidGenomes::makeGRangesFromEnsembl(...)
 2.   └─AcidGenomes:::.getEnsDb(...)
 3.     └─AcidGenomes:::.getEnsDbAnnotationHubID(...)
 4.       ├─goalie::assert(...)
 5.       └─AcidBase::requireNamespaces("AnnotationHub")
 6.         └─AcidBase:::.abort(...)
 7.           └─AcidCLI::abort(x)
 8.             └─cli::cli_abort(x, call = NULL)
 9.               └─rlang::abort(message, ..., call = call, use_cli_format = TRUE)
Execution halted
```

Furthermore, when I used the draft update tempalate you linked above, it get an error at line 108:
```
Quitting from lines 108-142 (FA_newTemplate.Rmd) 

Error:
! Assert failure.
[1] allAreInstalled(packages) is not TRUE.
Cause: org.NANA.eg.db: not installed
Backtrace:
    ▆
 1. └─goalie::assert(allAreInstalled(packages))
 2.   └─AcidCLI stop(...)
 3.     └─cli::cli_abort(x, call = NULL)
 4.       └─rlang::abort(message, ..., call = call, use_cli_format = TRUE)
Execution halted
```
Not sure what `org.NANA.eg.db` is as I tried to search for it to install but no install for NANA?

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh I couldnt get the tweaks to work so I ended up re-running the entire analysis from scratch creating the original bcb.rds object setting `organism` and `ensemblRelease`. I then ran this object through the DGE template to get a new deseq.rds object and ran this through the original Functional Analysis template. 

When keytype = geneName, this error:
```
preparing geneSet collections...
--> Expected input gene ID: ENSG00000130270,ENSG00000188488,ENSG00000133794,ENSG00000070770,ENSG00000158955,ENSG00000135624
Quitting from lines 329-363 (functional_analysis.Rmd) 

Error in `check_gene_id()`:
! --> No gene can be mapped....
Backtrace:
 1. clusterProfiler::gseGO(...)
 2. DOSE:::GSEA_internal(...)
 3. DOSE .GSEA(...)
 4. DOSE:::check_gene_id(geneList, geneSets)
Warning messages:
1: ggrepel: 1 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
2: ggrepel: 1 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
Execution halted
```

I also tried keytype = ensemblId, or entrezId, or geneId, but all gave erorrs from line 299
keytype = entrezId.... Error: Failed to map at least 50% of gene identifiers.
keytype = ensemblId...Error in as.vector(x, mode = "character"): no method for coercing this S4 class to a vector
keytype = geneId ...Error in as.vector(x, mode = "character"): no method for coercing this S4 class to a vector

**Comment by mjsteinbaugh** [comment]
Thanks I'm taking a look. Can you post or email a link to the `deseq` object used? That will make it much easier to debug. This may be an issue with [clusterProfiler](https://bioconductor.org/packages/clusterProfiler/) and [DOSE](https://www.bioconductor.org/packages/DOSE/).

**Comment by mjsteinbaugh** [comment]
It's this part, correct?

```r
gseaGo <- clusterProfiler::gseGO(
    geneList = rankedListEnsembl,
    ont = params[["go_class"]],
    OrgDb = get(orgDb, envir = asNamespace(orgDb)),
    keyType = "ENSEMBL",
    pvalueCutoff = 0.05
)
```

Can you print what `rankedListEnsembl` looks like on your machine?

**Comment by mjsteinbaugh** [comment]
Here's a minimal example that should work:

```r
suppressPackageStartupMessages({
    library(DESeqAnalysis) # 0.6.4
    library(AcidGSEA) # 0.8.4
})
data(deseq, package = "DESeqAnalysis")
ensembl <- RankedList(
    object = deseq,
    value = "stat",
    keyType = "ensemblId"
)
print(ensembl)
## RankedList of length 2
## names(2): condition_B_vs_A treatment_D_vs_C
print(head(ensembl[[1L]]))
# ENSG00000004848 ENSG00000008118 ENSG00000015133 ENSG00000011451 ENSG00000005100
#        4.681582        4.532673        4.309957        4.048786        3.993137
# ENSG00000007545
#        3.916430
entrez <- RankedList(
    object = deseq,
    value = "stat",
    keyType = "entrezId"
)
print(entrez)
## RankedList of length 2
## names(2): condition_B_vs_A treatment_D_vs_C
print(head(entrez[[1L]]))
##   170302    57172   440193    58525    56919    57585
## 4.681582 4.532673 4.309957 4.048786 3.993137 3.916430
```

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh I sent you a googledrive link to my deseq.rds object (mike@steinbaugh.com ?). 
Will test out the above shortly.

**Comment by mjsteinbaugh** [comment]
Perfect thanks! I'll try debugging with your dataset later today

**Comment by VictoriaPatten** [comment]
@mjsteinbaugh not sure if what I'm doing is correct. I tried to run the above minimal example you sent added in to the template at the start of the GO GSEA Analysis section, and get this error:
```
ℹ 97.6% of genes mapped to primary seqnames (57323 / 58735).

ℹ 97.6% of genes mapped to primary seqnames (57323 / 58735).
ℹ Mapping 43.5% of genes to `entrezId` (24936 / 57323).

Quitting from lines 299-347 (functional_analysis.Rmd) 

Error:
! BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error: Failed to map at least 50% of gene identifiers.
Backtrace:
  1. rmarkdown::render(...)
  2. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  6. knitr:::process_group.block(group)
  7. knitr:::call_block(x)
     ...
 12. knitr (local) evaluate(...)
 13. evaluate::evaluate(...)
 14. evaluate:::evaluate_call(...)
 19. evaluate:::eval_with_user_handlers(expr, envir, enclos, user_handlers)
 23. base::eval(expr, envir, enclos)
Warning messages:
1: ggrepel: 1 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
2: ggrepel: 1 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
Execution halted
```

The Package versions are all up to date

**Comment by mjsteinbaugh** [comment]
@VictoriaPatten I know how to fix the functional analysis template to get your dataset to work. I'll push a couple of changes to DESeqAnalysis and AcidGSEA that should fix the issue.

**Comment by mjsteinbaugh** [comment]
The minimal example won't work in the R Markdown template, it was just to check that your installation is working as expected

**Comment by VictoriaPatten** [comment]
Hi @mjsteinbaugh have you managed to push those changes? Sorry to bug you about it but my thesis submission deadline is next week so I'm on the wire and stressing to get this finished.

**Comment by mjsteinbaugh** [comment]
@VictoriaPatten Sure thing, I'll send an update later today

**Comment by mjsteinbaugh** [comment]
@VictoriaPatten Almost done, will push a couple of updates to AcidGSEA and bcbioRNASeq in the morning. I'll upload the R Markdown templates and the render files to your Google Drive tomorrow.

**Comment by mjsteinbaugh** [comment]
OK I think the AcidGSEA 0.8.5 update I just pushed should fix the issue you're having with the `RankedList` generator step for Ensembl-to-Entrez identifier mapping. I'll double check the Markdown template and send you an update in the morning.

**Comment by mjsteinbaugh** [comment]
@VictoriaPatten This should be resolved with the FA template update. Let me know if you run into any additional issues.
