### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kokyriakidis** [hbc/bcbioRnaseq#185]
Hi!

I get the following when I try to install bcbiornaseq

```
Error: object ‘geometricMean’ is not exported by 'namespace:AcidBase'
Execution halted
ERROR: lazy loading failed for package ‘AcidExperiment’
* removing ‘/home/kokyriakidis/R/x86_64-pc-linux-gnu-library/4.2/AcidExperiment’
Warning in install.packages :
  installation of package ‘AcidExperiment’ had non-zero exit status
```

**Comment by mjsteinbaugh** [comment]
Hi @kokyriakidis , what does this return for that R library:

```r
BiocManager::valid(site_repository = "http://r.acidgenomics.com")
```

**Comment by mjsteinbaugh** [comment]
For reference, current version of AcidBase is 0.6.5, AcidExperiment is 0.4.3.

**Comment by kokyriakidis** [comment]
On a new conda env the only way conda env is solved is like this:

```
r-acidbase-0.5.0           |    r41hdfd78af_0         209 KB  bioconda
    r-acidcli-0.2.0            |    r41hdfd78af_0          59 KB  bioconda
    r-acidexperiment-0.3.0     |    r41hdfd78af_0         657 KB  bioconda
    r-acidgenerics-0.6.0       |    r41hdfd78af_0         444 KB  bioconda
    r-acidgenomes-0.3.0        |    r41hdfd78af_0         677 KB  bioconda
    r-acidgsea-0.7.0           |    r41hdfd78af_0         1.3 MB  bioconda
    r-acidmarkdown-0.1.6       |    r41hdfd78af_0          83 KB  bioconda
    r-acidplots-0.4.0          |    r41hdfd78af_0         562 KB  bioconda
    r-acidplyr-0.2.0           |    r41hdfd78af_0         121 KB  bioconda
    r-acidsinglecell-0.2.0     |    r41hdfd78af_0         750 KB  bioconda
    r-base-4.1.3               |       h06d3f91_1        24.6 MB  conda-forge
```

How do you manage the installation? Maybe it is time to start pinning? eg. R=4.2.0

**Comment by mjsteinbaugh** [comment]
Yeah the conda environment will get updated when `r-base` 4.2.0 is available on conda-forge. Track the issue here: https://github.com/conda-forge/r-base-feedstock/pull/205

**Comment by mjsteinbaugh** [comment]
I'll see if I can hotfix this for the R 4.1.3 release series in the meantime.

**Comment by mjsteinbaugh** [comment]
How is this library `/home/kokyriakidis/R/x86_64-pc-linux-gnu-library/4.2` being managed? Did you try upgrading the packages inside of a conda install or is this a failure of the `r-bcbiornaseq` bioconda recipe?

**Comment by mjsteinbaugh** [comment]
PS clean install of current bioconda recipe does work, but is behind current stable release due to lack of R 4.2 on conda at the moment.

```sh
conda create --name='r-bcbiornaseq@0.4.0' 'r-bcbiornaseq==0.4.0'
conda activate 'r-bcbiornaseq@0.4.0'
R
```

```r
library(bcbioRNASeq)
packageVersion("bcbioRNASeq")
## 0.4.0
```

**Comment by kokyriakidis** [comment]
I tried to install R=4.2.0 and then install all packages from inside R but I always get errors in a lkot of packages. Sticking with r-bcbiornaseq@0.4.0 might be the only solution right now.

**Comment by kokyriakidis** [comment]
Hi @mjsteinbaugh 

Any news about the new conda version of r-bcbiornaseq?

**Comment by mjsteinbaugh** [comment]
Bioconda is still stuck with the conda-forge R 4.2 migration, so we can't use Bioconductor 3.15 -- hopefully there's an update this month
