### ISSUE TITLE
Differential Expression Analysis

### ISSUE THREAD

**Issue by mfcesur** [hbc/bcbioRnaseq#188]
Hi, 

I am trying to perform differential expression analysis for an RNA-seq dataset, whose count matrices were generated via the bcbioRNAseq package, and it seems to be normalized by the library size due to the use of "tximport-compatible caller".  The classical DESeq2 package also applies the library size normalization. Therefore, I cannot use this package for this dataset. On the other hand, I could perform the differential expression analysis via the _DESeq_ function in the bcbioRNAseq package. Doesn't this function apply  the library size normalization?

In addition, I could retrieve the statistical results (e.g., p-value and log2(fold_change)) using _results_ function (like the classical DESeq2 package) after the differential expression analysis. Are there any alternative functions in the bcbioRNAseq package to extract this statistical information, or do you recommend the use of this function (_results_)?

Best Regards,
Müberra

**Comment by mjsteinbaugh** [comment]
Hi @mfcesur give this a try and let me know if it works for your downstream processing with DESeq2.

```r
library(bcbioRNASeq)
## Assuming "object" is a bcbioRNASeq object.
## Will return a `DESeqDataSet` object for use with DESeq2.
dds <- as.DESeqDataSet(object)
```

Best,
Mike

**Comment by mfcesur** [comment]
Differential expression analysis using DESeq2 works for **dds <- as.DESeqDataSet(bcb)**. 

However, _DESeqDataSetFromMatrix_ function gives error for the preprocessed data (normalized by the library size) due to the presence of non-integer values. I should ensure whether an additional library size normalization is applied by the _DESEq_ function in the bcbioRNASeq package, because my dataset has been already normalized by the library size.

Best Regards,
Müberra

**Comment by mjsteinbaugh** [comment]
Hi @mfcesur you don't need to use `DESeqDataSetFromMatrix` to prepare DESeq2. I'd recommend against that in favor of using our coercion method above, or take a look at `DESeqDataSetFromTximport`, using tximport directly instead. This is what the bcbioRNASeq package does internally.

Here's the code responsible for that:
https://github.com/hbc/bcbioRNASeq/blob/master/R/internal-tximport.R
https://github.com/hbc/bcbioRNASeq/blob/master/R/internal-DESeq2.R

Refer to the DESeq2 vignette for details:
https://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html

I think you're looking for this:

```r
## Here object is your bcbioRNASeq object.
counts <- counts(object, normalized = FALSE)
counts <- round(counts, digits = 0L)
mode(counts) <- "integer"
```

**Comment by mjsteinbaugh** [comment]
Please reopen if this remains an issue

**Comment by mfcesur** [comment]
Thank you so much for your detailed comments and the related links.

Sincerely,
Müberra
