### ISSUE TITLE
Issues with templates: Differential Expression & Functional Analysis

### ISSUE THREAD

**Issue by Adrian-Zet** [hbc/bcbioRnaseq#189]
Dear bcbioRNASeq team,

I 
have a complex issue, the first one I also commented in a closed issue (yet I think it's different enough to add here, in it's own topic)

So I ran bcbio on a dataset with breast cancer and asymptomatic controls. And decided to use the template for differential expression. All went well except the multiple contrasts. As you can see I only have 2 conditions (asymptomatic control vs breast cancer). Is it possible to just declare this one contrast?

When I run the code I get the following error:

Error in `checkContrast()`:
! 'contrast' vector should be either a character vector of length 3,
a list of length 2 containing character vectors,
or a numeric vector, see the argument description in ?results
(I also got a different error when I tried something like:

contrasts: !r list(
      "breastCancer_vs_asymptomaticControls" = c(
        "factor" = "group",
        "numerator" = "Asymptomatic.Controls",
        "denominator" = "Breast.Cancer"
      ),
      "asymptomaticControls_vs_breastCancer" = c(
        "factor" = "group",
        "numerator" = "Breast.Cancer",
        "denominator" = "Asymptomatic.Controls"
      )
    )
Also, when I tried to see the resultsNames(dds) - it only lists "Intercept" column.

The interestingGroups of the object are ("group").
I list the whole object import here:

object <- bcbioRNASeq(
uploadDir = file.path("final"),
interestingGroups = c("group"),
organism = "Homo sapiens"
)

Also here is the .yaml resulted from running bcbio (changed it to .txt since it doesn't support uploading .yaml)
[project-summary.txt](https://github.com/hbc/bcbioRNASeq/files/10121678/project-summary.txt)

Please provide a feedback on how I should build the contrasts for this template, or maybe if there is a way to completely bypass the contrasts for this case.

### The second issue has to do with the Functional analysis template when I ran it it gave me the following error:

```
Quitting from lines 56-97 (funcitonaltest.rmd) 
Error in library(clusterProfiler) : 
  there is no package called 'clusterProfiler'
Calls: cat ... suppressPackageStartupMessages -> withCallingHandlers -> library

```
Now, I did try to install the required library(clusterProfiler), yet I encountered errors with the subpackages that are being used by the other library (bcbioRNASeq) and it gave me the following error:

```
Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/export/home/math/saia/R-4.2.1/lib/R/library/00LOCK-igraph/00new/igraph/libs/igraph.so':
  libgfortran.so.4: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/export/home/math/saia/R-4.2.1/lib/R/library/igraph’
* installing *source* package ‘ggtree’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ggtree)
ERROR: dependency ‘igraph’ is not available for package ‘tidygraph’
* removing ‘/export/home/math/saia/R-4.2.1/lib/R/library/tidygraph’
ERROR: dependency ‘igraph’ is not available for package ‘graphlayouts’
* removing ‘/export/home/math/saia/R-4.2.1/lib/R/library/graphlayouts’
ERROR: dependencies ‘igraph’, ‘tidygraph’, ‘graphlayouts’ are not available for package ‘ggraph’
* removing ‘/export/home/math/saia/R-4.2.1/lib/R/library/ggraph’
ERROR: dependencies ‘ggraph’, ‘igraph’ are not available for package ‘enrichplot’
* removing ‘/export/home/math/saia/R-4.2.1/lib/R/library/enrichplot’
ERROR: dependency ‘enrichplot’ is not available for package ‘clusterProfiler’
* removing ‘/export/home/math/saia/R-4.2.1/lib/R/library/clusterProfiler’

The downloaded source packages are in
        ‘/tmp/user/1233/RtmpMzLcj5/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages(...) :
  installation of package ‘igraph’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘tidygraph’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘graphlayouts’ had non-zero exit status
4: In install.packages(...) :
  installation of package ‘ggraph’ had non-zero exit status
5: In install.packages(...) :
  installation of package ‘enrichplot’ had non-zero exit status
6: In install.packages(...) :
  installation of package ‘clusterProfiler’ had non-zero exit status
```

Please provide some feedback related to both issues. 

Thank you,
Adrian

**Comment by mjsteinbaugh** [comment]
Hi @Adrian-Zet ,

Thanks for getting in touch. First, let me see if I can help you figure out the configuration issue with your R installation. Can you provide the return of `sessionInfo()` from R?

**Comment by Adrian-Zet** [comment]
Hi @mjsteinbaugh,

Thanks for the help. I'll begin with an update, I followed some threads on the clusterProfiler github page, and managed to solve the issue with its installation. So now all I have to do is to understand/fix the contrast setup.

Here is the sessionInfo():

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /export/home/math/saia/R-4.2.1/lib/R/lib/libRblas.so
LAPACK: /export/home/math/saia/R-4.2.1/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1 cli_3.4.1      jsonlite_1.8.4 rlang_1.0.6   
``` 

For anyone struggling with the same issues I had with clusterProfiler here are some links to the threads with the fixes (https://github.com/igraph/rigraph/issues/275#issuecomment-947940126)

**Comment by mjsteinbaugh** [comment]
@Adrian-Zet It may be helpful to walk through the R Markdown template step by step. Reading through your issue above, were you able to get to the step at [line 187 in the template](https://github.com/hbc/bcbioRNASeq/blob/v0.5.1/inst/rmarkdown/templates/02-differential-expression/skeleton/skeleton.Rmd#L187)?

`dds <- DESeq(dds)`

If so, does `resultsNames` still only return `Intercept`? What does `design(dds)` return?

**Comment by Adrian-Zet** [comment]
**Edit-Final:** So I manged to solve the issue. Apparently all I had to do was use a single contrast having the denominator and numerator named exactly like in the metadata file (e.g. "Breast Cancer" instead of "Breast.Cancer"). Something I read in the vignettes made me think that I should use the Breast.Cancer notation. Anyway, a lesson learned was to never use " " (spaces) in "group" column. It seems the problem is solved for the Differential Expression template, yet it still occurs in the Functional Analysis one, I guess I either have to change the metadata or to rerun the experiment using a different naming convention. 

Anyway, thanks for the help. You can close the thread after reviewing my answer.

========================================================
(Redundant but kept for further notice:)
Now the function resultsNames(dds) gives me the following output:

```
> resultsNames(dds)
[1] "Intercept"                                   
[2] "group_Breast.Cancer_vs_Asymptomatic.Controls"
```

Below is the error specifying the line with the issues:
```

Quitting from lines 222-231 (Deseq-test.rmd) 

Error in `checkContrast()`:
! 'contrast' vector should be either a character vector of length 3,
a list of length 2 containing character vectors,
or a numeric vector, see the argument description in ?results
Backtrace:
 1. BiocGenerics::Map(...)
 6. base::Map(f = f, ...)
 7. base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
 8. DESeq2 (local) `<fn>`(...)
 9. DESeq2:::checkContrast(contrast, resNames)



Execution halted

[VSC-R] Deseq-test.rmd process exited with exit code 1
[VSC-R] terminating R process
```

I also tried running only lines from the template without knitting it but I always end up with the following error:
```

Error in (function (cond)  : 
  error in evaluating the argument 'X' in selecting a method for function 'lapply': object of type 'closure' is not subsettable
```

The contrasts were specified by me as it follows:
```

 ## Multiple contrasts are supported. Ensure that each contrast is named.
  contrasts: !r list(
      "breastCancer_vs_asymptomaticControls" = c(
        "factor" = "group",
        "numerator" = "Asymptomatic.Controls",
        "denominator" = "Breast.Cancer"
      ),
      "asymptomaticControls_vs_breastCancer" = c(
        "factor" = "group",
        "numerator" = "Breast.Cancer",
        "denominator" = "Asymptomatic.Controls"
      )
    )
```

I believe the error might also be related to not understanding exactly how to specify the contrasts correctly, also I would like to keep just the first one (I don't need Multiple Contrasts for this use case).

Here's also a sample from the CSV with the metadata:

<html>
<body>
<div class="clickup-table-view">

samplename | description | group
-- | -- | --
SRR15780669 | Blood_Platelets_24 | Asymptomatic Controls
SRR15780956 | Blood_Platelets_H181 | Breast Cancer

</div>
</body>
</html>

P.S. The template I'm using was Updated 2022-09-01 and generated by the bcbioRNASeq R Library version (bcbioRNASeq_0.5.1).

**Comment by mjsteinbaugh** [comment]
Great job debugging this!
