### ISSUE TITLE
`_setup.R` file needs to be updated.

### ISSUE THREAD

**Issue by jxshi** [hbc/bcbioRnaseq#195]
Hi guys,

Since the function `scale_color_synesthesia_c` in `AcidPlots` package has been updated to `acid_scale_color_synesthesia_c`, the corresponding code in `_setup.R` file needs to be updated.
```
## Set default ggplot2 colors and theme.
options(
    "ggplot2.continuous.colour" =
        AcidPlots::scale_color_synesthesia_c,
    "ggplot2.continuous.fill" =
        AcidPlots::scale_fill_synesthesia_c,
    "ggplot2.discrete.colour" =
        AcidPlots::scale_color_synesthesia_d,
    "ggplot2.discrete.fill" =
        AcidPlots::scale_fill_synesthesia_d
)

```
Updated version:
```
## Set default ggplot2 colors and theme.
options(
    "ggplot2.continuous.colour" =
        AcidPlots::acid_scale_color_synesthesia_c,
    "ggplot2.continuous.fill" =
        AcidPlots::acid_scale_fill_synesthesia_c,
    "ggplot2.discrete.colour" =
        AcidPlots::acid_scale_color_synesthesia_d,
    "ggplot2.discrete.fill" =
        AcidPlots::acid_scale_fill_synesthesia_d
)
```

**Comment by jxshi** [comment]
According to the following error message:
```
! Error from the generic function 'plotMA' defined in package 'BiocGenerics': no S4 method definition for argument 'object' of class 'DESeqAnalysis' was found. Did you perhaps mean calling the function 'plotMA' from another package, e.g. 'limma'? In that case, please use the syntax 'limma::plotMA'.
```
The following template `inst/rmarkdown/templates/02-differential-expression/skeleton/skeleton.Rmd`, line 279 also needs to be updated:
```
print(plotMa(object = object, i = i))
```
Updated version:
```
print(limma::plotMA(object = object, i = i))
```

**Comment by mjsteinbaugh** [comment]
Thanks @jxshi I'll make a couple tweaks to these templates. Note that `plotMa` is correct -- we're not using the BiocGenerics variant here.

**Comment by mjsteinbaugh** [comment]
It looks like you may need to update your R packages -- what does `utils::sessionInfo` return?

Current `_setup.R` file is here:
https://github.com/acidgenomics/r-acidmarkdown/blob/main/inst/rmarkdown/shared/_setup.R

You can check whether your library is current with:

```r
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
install.packages(
    pkgs = "AcidDevTools",
    repos = c(
        "https://r.acidgenomics.com",
        BiocManager::repositories()
    ),
    dependencies = TRUE
)
AcidDevTools::valid()
```

**Comment by jxshi** [comment]
Hi @mjsteinbaugh,

Thank you for your timely reply! You are right, the `AcidDevTools` package is outdated and needs to be updated. After updating this package, the issue is resolved.

Best,
Jianxiang
