### ISSUE TITLE
Add chromosome to metadata

### ISSUE THREAD

**Issue by lpantano** [hbc/bcbioRNASeq#52]
Some times consults are interested in specific chromosomes. It would be good to have them there.

**Comment by mjsteinbaugh** [comment]
Agreed – originally this was added with the annotables from biomaRt. Currently we're using AnnotationHub with ensembldb, which uses GenomicRanges. We'll have to map the coordinates to the chromosomes and add that as a column. I'll work on adding that this week. It will be useful for QC on sexually dimorphic genes as well.

**Comment by mjsteinbaugh** [comment]
This is added in the latest [basejump](https://github.com/steinbaugh/basejump) update:

**[AnnotationHub](https://www.bioconductor.org/packages/release/bioc/html/AnnotationHub.html) via [ensembldb](http://bioconductor.org/packages/release/bioc/html/ensembldb.html).** Recommended default method. Versioned support for most genomes, including GRCh38/hg38, GRCm38/mm10. It uses GenomicRanges to map the coordinates, and chromosome typically maps to the `seqName` column. Scaffolds are also included, which you can see in the `seqCoordSystem` column.

```
anno <- basejump::annotable("Mus musculus")
```

**[annotables](https://github.com/stephenturner/annotables).** Alternative method, using precompiled tibbles from biomaRt. This supports GRCh37/hg19. Chromosomes are in the `chr` column.

```
anno <- basejump::annotables(annotables::grch37)
```
