### ISSUE TITLE
detectOrganism fails with non standards organisms

### ISSUE THREAD

**Issue by lpantano** [hbc/bcbioRNASeq#57]
`basejump::detectOrganism` shouldn't fail, just gives a warning. This way bcbioRNASeq is compatible with any genome. Right now even is `annotable` is NULL, the `loadRNASeq` function fails.

https://github.com/hbc/bcbioRNASeq/blob/master/R/loadRNASeq.R#L154

https://github.com/steinbaugh/basejump/blob/master/R/methods-detectOrganism.R#L150

**Comment by mjsteinbaugh** [comment]
Thanks I'll work on pushing a fix for that

**Comment by mjsteinbaugh** [comment]
This should be fixed in the [basejump](http://steinbaugh.com/basejump) 0.0.12 update.
