### ISSUE TITLE
Installation on CentOS failed

### ISSUE THREAD

**Issue by hliu2016** [hbc/bcbioRNASeq#60]
I have successfully installed bcbioRNASeq on Windows 10 platform. Now I try to install bcbioRNASeq on Linux. My server OS is CentOS 7， I run the following R command:
```
source("https://bioconductor.org/biocLite.R")
biocLite(
    "hbc/bcbioRNASeq",
    dependencies = c("Depends", "Imports", "Suggests")
)
```
I only got

> BioC_mirror: https://bioconductor.org
> Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.1 (2017-06-30).
> Installing github package(s) ‘hbc/bcbioRNASeq’
> Downloading GitHub repo hbc/bcbioRNASeq@master
> from URL https://api.github.com/repos/hbc/bcbioRNASeq/zipball/master
> Installation failed: error in running command

My network connention is OK, and I have successfully installed other R packages. 
I have tried many times to install bcbioRNASeq but it always failed. Do you have any idea?

**Comment by mjsteinbaugh** [comment]
Do any other GitHub packages install correctly? It sounds like this is an issue with the [devtools](https://github.com/hadley/devtools) package, which is required to install R packages from GitHub. 

How did you install R on CentOS? Did you compile it from source? You may need to ensure that your `PATH`, `LD_RUN_PATH`, and `PKG_CONFIG_PATH` environmental variables are configured correctly.

**Comment by hliu2016** [comment]
@mjsteinbaugh 
Thanks for your reply. I am using the R that is automatically installed by bcbio. The R Home directory is the $BCBIO_HOME/anaconda/lib/R. I have set the PATH environmental variable to include R's bin directory.

How should I set the LD_RUN_PATH, and PKG_CONFIG_PATH environmental variables?

**Comment by mjsteinbaugh** [comment]
It may depend on your anaconda configuration, but here's how I have my miniconda installation set to use R on a CentOS-based HPC cluster:

```
export CONDA_DIR="$HOME/miniconda3"
export PATH="$CONDA_DIR/bin:$PATH"
export LD_RUN_PATH="$CONDA_DIR/lib:$LD_RUN_PATH"
export PKG_CONFIG_PATH="$CONDA_DIR/lib/pkgconfig:$PKG_CONFIG_PATH"
```

https://github.com/steinbaugh/seqcloud/blob/master/profile/path/01_conda.sh
