### ISSUE TITLE
## Error in detach("package:dplyr", unload = TRUE): invalid 'name' argument

### ISSUE THREAD

**Issue by hliu2016** [hbc/bcbioRNASeq#65]
Hi, I am using bcbioRNASeq's  functional annotation RMarkDown template to do functional analysis. But this error occurred in the KEGG GSEA analysis section. How to tackle this problem? Thanks a lot.

**Comment by mjsteinbaugh** [comment]
Hi @hliu2016 are you still having issues with dplyr in the functional analysis template?

**Comment by mjsteinbaugh** [comment]
Closed due to inactivity
