### ISSUE TITLE
bioconductor connection

### ISSUE THREAD

**Issue by Safary1094** [hbc/bcbioRNASeq#81]
Error while project loading:

```
> bcb = loadRNASeq(uploadDir = project_path, interestingGroups = interest_gr)
2017-09-21_bcbio_rnaseq
4 samples detected
Reading project-summary.yaml
Genome: Homo sapiens (hg38)
Error in value[[3L]](cond) : failed to connect
reason: Failed to connect to bioconductor.org port 80: Connection refused
Consider rerunning with 'localHub=TRUE'
```

OS:  Red Hat Enterprise Linux Server release 6.5

P.S. Ubuntu 17.10: the same code works fine

**Comment by mjsteinbaugh** [comment]
Hi @Safary1094,

Running R on Red Hat, does either of these work?

```r
# HTTPS
source("https://bioconductor.org/biocLite.R")

# HTTP
source("http://bioconductor.org/biocLite.R")
```

It looks like the HPC is having trouble connecting to Bioconductor, or the Bioconductor website went down temporarily.

`loadRNASeq()` connects to Biocondcutor to get the gene annotations from Ensembl using AnnotationHub and ensembldb when `annotable = TRUE` (default). You can skip loading gene annotations with `annotable = NULL`, but that isn't generally recommended.

Best,
Mike

**Comment by Safary1094** [comment]
sorry for wrong issue. There was incorrect proxy setting on HPC. Now everything works fine!

**Comment by mjsteinbaugh** [comment]
Great to hear!
