### ISSUE TITLE
Error : object 'assertFormalAnnotationCol' is not exported by 'namespace:basejump'

### ISSUE THREAD

**Issue by hliu2016** [hbc/bcbioRNASeq#89]
Hi, I tried to install bcbioRNAseq but failed because of this error. Is there any method to work out it?

> BioC_mirror: https://bioconductor.org
> Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
> Installing github package(s) ‘hbc/bcbioRNASeq’
> Downloading GitHub repo hbc/bcbioRNASeq@master
> from URL https://api.github.com/repos/hbc/bcbioRNASeq/zipball/master
> Installing bcbioRNASeq
> "C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/hliu/AppData/Local/Temp/RtmpqWGgRC/devtools2bb03c0848cd/hbc-bcbioRNASeq-c7fa7dc"  \
>   --library="C:/Users/hliu/Documents/R/win-library/3.4" --install-tests 
> 
> * installing *source* package 'bcbioRNASeq' ...
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** tests
> ** preparing package for lazy loading
> Error : object 'assertFormalAnnotationCol' is not exported by 'namespace:basejump'
> ERROR: lazy loading failed for package 'bcbioRNASeq'
> * removing 'C:/Users/hliu/Documents/R/win-library/3.4/bcbioRNASeq'
> In R CMD INSTALL
> Installation failed: Command failed (1)

**Comment by mjsteinbaugh** [comment]
Hi @hliu2016, I think your install has the newest version of basejump but bcbioBase is a version behind. Try running `devtools::install_github("hbc/bcbioBase")`.

**Comment by mjsteinbaugh** [comment]
Hi @hliu2016,

Thanks, I'm working on pushing some changes to bcbioRNASeq that involve updates in the basejump and bcbioBase dependency packages. We're still testing the bcbioRNASeq code but will push the changes here soon. We're working on getting the package submitted to Bioconductor so we can maintain a stable release there.

In the meantime, you can roll back the dependencies in your local library and this should get bcbioRNASeq working again:

```
library(devtools)
install_github("steinbaugh/basejump", ref = "v0.4.0", dependencies = FALSE)
install_github("hbc/bcbioBase", ref = "v0.2.0", dependencies = FALSE)
```

Best,
Mike

**Comment by hliu2016** [comment]
Hi @mjsteinbaugh,
Thanks for your answer. However, I have removed the bcbioRNAseq package. So, even if I install the basejump and bcbioBase packages according your suggestion, I can not install bcbioRNAseq because the newest version of basejump and bcbioBase will be automatically installed before the bcbioRNAseq installation. Is there any other method to make bcbioRNASeq  work?

**Comment by mjsteinbaugh** [comment]
Sure, here's how you can do that:

```r
library(devtools)
install_github("steinbaugh/basejump", ref = "v0.4.0", dependencies = FALSE)
install_github("hbc/bcbioBase", ref = "v0.2.0", dependencies = FALSE)

install_github("hbc/bcbioRNASeq", dependencies = FALSE)
```

Just set `dependencies = FALSE` and R won't attempt to install any of the dependencies from GitHub automatically. Like I mentioned, we working on getting this up on Bioconductor so installation is easier in the future!
