### ISSUE TITLE
KEGG plots fail in Funcitonal analysis template

### ISSUE THREAD

**Issue by jnhutchinson** [hbc/bcbioRNASeq#97]
pathview command is running on lfc_vec and not entrez_lfc_vec

**Comment by mjsteinbaugh** [comment]
Thanks John I'll look into this. We need to add the FA template to our automated build checks.

**Comment by mjsteinbaugh** [comment]
Hi @hliu2016 I'm working on adding automatic unit testing to our functional analysis code and will push a fix for this soon.

**Comment by mjsteinbaugh** [comment]
This should be fixed in the latest bcbioRNASeq release (v0.2.4).
